"use client";

import GeneratorTool from "@/app/components/tools/GeneratorTool";

const RISKS = [
  { value: "critical", label: "Critical" },
  { value: "high", label: "High" },
  { value: "medium", label: "Medium" },
  { value: "low", label: "Low" },
  { value: "informational", label: "Informational" },
];

export default function SecurityReportPage() {
  return (
    <GeneratorTool
      title="Security Report Generator"
      description="Turn a finding into a clean security report — executive summary, technical detail, risk rating, affected systems and remediation plan."
      skill="Risk communication, security report writing."
      why="Stops findings dying in tickets. Gives leadership a defensible written record."
      futureApi="Wire to Defender XDR, Microsoft Secure Score, or Vanta findings to seed the report automatically."
      outputBadge="Demo report · refine before sharing externally"
      inputs={[
        { id: "title", label: "Finding title", placeholder: "Public S3 bucket exposes customer invoices", required: true, span: "full" },
        { id: "system", label: "Affected system / asset", placeholder: "invoices.contoso.com / aws-s3 prod-invoices", required: true },
        { id: "risk", label: "Risk level", type: "select", options: RISKS, defaultValue: "high", required: true },
        { id: "owner", label: "Owner / accountable team", placeholder: "Platform team" },
        { id: "summary", label: "Executive summary", type: "textarea", placeholder: "What was found and why it matters.", span: "full", required: true },
        { id: "evidence", label: "Evidence / detail", type: "textarea", placeholder: "Logs, screenshots, repro steps.", span: "full" },
      ]}
      generate={(v) => {
        if (!v.title || !v.summary) return "";
        const riskLabel = RISKS.find((r) => r.value === v.risk)?.label ?? "Medium";
        const today = new Date().toISOString().slice(0, 10);
        const lines: string[] = [];
        lines.push(`# Security Report — ${v.title}`);
        lines.push("");
        lines.push(`**Date:** ${today}`);
        lines.push(`**Risk:** ${riskLabel}`);
        lines.push(`**Affected system:** ${v.system || "—"}`);
        if (v.owner) lines.push(`**Owner:** ${v.owner}`);
        lines.push("");
        lines.push("## 1. Executive summary");
        lines.push(v.summary);
        lines.push("");
        lines.push("## 2. Impact");
        const impactByRisk: Record<string, string> = {
          critical: "Active exploitation likely; immediate business, regulatory or financial impact.",
          high: "Significant data, reputational or operational impact without remediation.",
          medium: "Plausible exploitation requiring chained conditions; remediate within standard SLA.",
          low: "Limited exploitability and impact; remediate as housekeeping.",
          informational: "No direct exploitability; noted for completeness.",
        };
        lines.push(`- ${impactByRisk[v.risk] ?? impactByRisk.medium}`);
        lines.push("- Confidentiality / Integrity / Availability dimension(s) affected — confirm during triage.");
        lines.push("");
        lines.push("## 3. Technical detail");
        lines.push(v.evidence || "_No evidence provided. Attach logs, screenshots, or reproduction steps._");
        lines.push("");
        lines.push("## 4. Remediation");
        if (v.risk === "critical" || v.risk === "high") {
          lines.push("- [ ] Apply emergency mitigation within 24h (block, isolate, hide).");
          lines.push("- [ ] Permanent fix within 7 days; track to closure.");
          lines.push("- [ ] Notify affected stakeholders per incident comms plan.");
        } else if (v.risk === "medium") {
          lines.push("- [ ] Schedule fix within the next 30 days.");
          lines.push("- [ ] Add detection / compensating control in the meantime.");
        } else {
          lines.push("- [ ] Add to next maintenance window.");
          lines.push("- [ ] Document compensating controls already in place.");
        }
        lines.push("");
        lines.push("## 5. Verification");
        lines.push("- [ ] Re-test the original finding once remediation is deployed.");
        lines.push("- [ ] Add a regression check / detection rule to prevent recurrence.");
        lines.push("");
        lines.push("## 6. Sign-off");
        lines.push("- [ ] Security review: ");
        lines.push("- [ ] Service owner: ");
        lines.push("- [ ] Closure date: ");
        lines.push("");
        lines.push("---");
        lines.push("_Generated by SecureScope. Edit to match your reporting template before distribution._");
        return lines.join("\n");
      }}
    />
  );
}
