"use client";

import GeneratorTool from "@/app/components/tools/GeneratorTool";

export default function QaReportPage() {
  return (
    <GeneratorTool
      title="Website QA Report Generator"
      description="Convert completed tests, failed items and required fixes into a polished QA sign-off doc."
      skill="QA reporting, release management."
      why="Closes the loop between testing and release. Gives PMs and stakeholders something to sign."
      futureApi="Wire to Playwright / Cypress JSON results to auto-populate the pass/fail table."
      outputBadge="Demo report · adapt to your release cadence"
      inputs={[
        { id: "site", label: "Site / release", placeholder: "example.com — 2026-05 marketing relaunch", required: true, span: "full" },
        { id: "env", label: "Environment", placeholder: "Production / Staging" },
        { id: "tester", label: "QA owner", placeholder: "Your name" },
        { id: "passed", label: "Tests passed (one per line)", type: "textarea", placeholder: "Homepage hero CTA renders correctly\nContact form sends to CRM", span: "full" },
        { id: "failed", label: "Tests failed (one per line)", type: "textarea", placeholder: "Pricing page broken on iOS Safari 320px\nFooter LinkedIn link 404s", span: "full" },
        { id: "fixes", label: "Fixes required (one per line)", type: "textarea", placeholder: "Adjust pricing grid breakpoint\nUpdate LinkedIn URL", span: "full" },
      ]}
      generate={(v) => {
        if (!v.site) return "";
        const list = (s: string) => (s || "").split(/\n+/).map((x) => x.trim()).filter(Boolean);
        const passed = list(v.passed);
        const failed = list(v.failed);
        const fixes = list(v.fixes);
        const today = new Date().toISOString().slice(0, 10);
        const total = passed.length + failed.length;
        const passRate = total > 0 ? Math.round((passed.length / total) * 100) : null;
        const lines: string[] = [];
        lines.push(`# Website QA Report — ${v.site}`);
        lines.push("");
        lines.push(`**Date:** ${today}`);
        if (v.env) lines.push(`**Environment:** ${v.env}`);
        if (v.tester) lines.push(`**QA owner:** ${v.tester}`);
        lines.push("");
        lines.push("## Summary");
        lines.push(`- **Tests executed:** ${total}`);
        lines.push(`- **Passed:** ${passed.length}`);
        lines.push(`- **Failed:** ${failed.length}`);
        lines.push(`- **Pass rate:** ${passRate === null ? "—" : `${passRate}%`}`);
        lines.push("");
        lines.push("## Passed");
        if (passed.length === 0) lines.push("- _No passed tests listed._");
        for (const p of passed) lines.push(`- ✅ ${p}`);
        lines.push("");
        lines.push("## Failed");
        if (failed.length === 0) lines.push("- _No failures — clean run._");
        for (const f of failed) lines.push(`- ❌ ${f}`);
        lines.push("");
        lines.push("## Fixes required before sign-off");
        if (fixes.length === 0) lines.push("- _None — release candidate is sign-off ready._");
        for (const f of fixes) lines.push(`- [ ] ${f}`);
        lines.push("");
        lines.push("## Sign-off");
        const ready = failed.length === 0 && fixes.length === 0;
        lines.push(`- **Recommendation:** ${ready ? "Approve for release." : "Hold until failed items / fixes are resolved."}`);
        lines.push("- [ ] QA owner");
        lines.push("- [ ] Product / engineering lead");
        lines.push("- [ ] Stakeholder sign-off");
        lines.push("");
        lines.push("---");
        lines.push("_Generated by SecureScope. Polish in your release template before sharing._");
        return lines.join("\n");
      }}
    />
  );
}
