"use client";

import {
  useEffect,
  useMemo,
  useState,
  type ChangeEvent,
  type ReactNode,
} from "react";
import ToolPageLayout from "@/app/components/tools/ToolPageLayout";

export interface ChecklistItem {
  id: string;
  label: string;
  hint?: string;
  defaultChecked?: boolean;
}

export interface ChecklistSection {
  title: string;
  description?: string;
  items: ChecklistItem[];
}

export interface ChecklistInput {
  id: string;
  label: string;
  placeholder?: string;
  type?: "text" | "email" | "date";
  defaultValue?: string;
  required?: boolean;
}

export interface ChecklistToolProps {
  title: string;
  description: string;
  /** Optional short skill/tag line shown alongside the tool intro. */
  skill?: string;
  /** Optional copy describing why this is useful to IT/security teams. */
  why?: string;
  /** Optional copy describing how this could later be wired to a real API. */
  futureApi?: string;
  inputs?: ChecklistInput[];
  sections: ChecklistSection[];
  /**
   * Optional function that turns the filled inputs into a few additional
   * checklist lines to inject above the sections in the output.
   */
  deriveSummary?: (values: Record<string, string>) => string[];
  /** When provided, the checklist state and inputs persist to localStorage. */
  storageKey?: string;
}

function progress(checked: number, total: number) {
  if (total === 0) return 0;
  return Math.round((checked / total) * 100);
}

function generateMarkdown(
  props: ChecklistToolProps,
  values: Record<string, string>,
  checks: Record<string, boolean>,
): string {
  const lines: string[] = [];
  lines.push(`# ${props.title}`);
  lines.push("");
  lines.push(`> Checklist output generated by SecureScope IT/Cyber Toolkit.`);
  lines.push("");
  if (props.inputs && props.inputs.length > 0) {
    lines.push("## Context");
    for (const input of props.inputs) {
      const v = (values[input.id] ?? "").trim();
      if (v) lines.push(`- **${input.label}:** ${v}`);
    }
    lines.push("");
  }
  if (props.deriveSummary) {
    const summary = props.deriveSummary(values);
    if (summary.length > 0) {
      lines.push("## Summary");
      for (const s of summary) lines.push(`- ${s}`);
      lines.push("");
    }
  }
  for (const section of props.sections) {
    lines.push(`## ${section.title}`);
    if (section.description) lines.push(`_${section.description}_`);
    for (const item of section.items) {
      const mark = checks[item.id] ? "x" : " ";
      lines.push(`- [${mark}] ${item.label}`);
      if (item.hint) lines.push(`    - _${item.hint}_`);
    }
    lines.push("");
  }
  lines.push("---");
  lines.push(`Generated ${new Date().toISOString()}`);
  return lines.join("\n");
}

export default function ChecklistTool(props: ChecklistToolProps) {
  const allItems = useMemo(
    () => props.sections.flatMap((s) => s.items),
    [props.sections],
  );

  const [values, setValues] = useState<Record<string, string>>(() => {
    const obj: Record<string, string> = {};
    for (const input of props.inputs ?? []) {
      obj[input.id] = input.defaultValue ?? "";
    }
    return obj;
  });

  const [checks, setChecks] = useState<Record<string, boolean>>(() => {
    const obj: Record<string, boolean> = {};
    for (const item of allItems) {
      obj[item.id] = Boolean(item.defaultChecked);
    }
    return obj;
  });

  const [copied, setCopied] = useState(false);

  useEffect(() => {
    if (!copied) return;
    const t = setTimeout(() => setCopied(false), 1800);
    return () => clearTimeout(t);
  }, [copied]);

  // Hydrate from localStorage when storageKey is supplied.
  useEffect(() => {
    if (!props.storageKey || typeof window === "undefined") return;
    try {
      const raw = window.localStorage.getItem(props.storageKey);
      if (!raw) return;
      const parsed = JSON.parse(raw) as { v?: Record<string, string>; c?: Record<string, boolean> };
      // Hydrating from localStorage — intentional client-side state restore.
      /* eslint-disable react-hooks/set-state-in-effect */
      if (parsed?.v) setValues((prev) => ({ ...prev, ...parsed.v }));
      if (parsed?.c) setChecks((prev) => ({ ...prev, ...parsed.c }));
      /* eslint-enable react-hooks/set-state-in-effect */
    } catch {
      /* ignore */
    }
  }, [props.storageKey]);

  useEffect(() => {
    if (!props.storageKey || typeof window === "undefined") return;
    try {
      window.localStorage.setItem(
        props.storageKey,
        JSON.stringify({ v: values, c: checks }),
      );
    } catch {
      /* ignore */
    }
  }, [props.storageKey, values, checks]);

  const checkedCount = Object.values(checks).filter(Boolean).length;
  const pct = progress(checkedCount, allItems.length);

  const output = useMemo(
    () => generateMarkdown(props, values, checks),
    [props, values, checks],
  );

  function setInput(id: string, e: ChangeEvent<HTMLInputElement>) {
    setValues((prev) => ({ ...prev, [id]: e.target.value }));
  }

  function toggle(id: string) {
    setChecks((prev) => ({ ...prev, [id]: !prev[id] }));
  }

  function checkAll(value: boolean) {
    const next: Record<string, boolean> = {};
    for (const item of allItems) next[item.id] = value;
    setChecks(next);
  }

  async function copy() {
    try {
      await navigator.clipboard.writeText(output);
      setCopied(true);
    } catch {
      setCopied(false);
    }
  }

  function downloadMarkdown() {
    const blob = new Blob([output], { type: "text/markdown;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    const slug = props.title.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, "");
    a.href = url;
    a.download = `${slug || "checklist"}.md`;
    document.body.appendChild(a);
    a.click();
    a.remove();
    URL.revokeObjectURL(url);
  }

  return (
    <ToolPageLayout title={props.title} description={props.description}>
      <ChecklistMeta skill={props.skill} why={props.why} futureApi={props.futureApi} />

      {props.inputs && props.inputs.length > 0 && (
        <div className="mb-6 rounded-[24px] border border-white/10 bg-[rgba(255,255,255,0.03)] p-5 backdrop-blur-xl">
          <p className="text-[11px] font-semibold uppercase tracking-[0.28em] text-white/45 mb-3">
            Context inputs
          </p>
          <div className="grid gap-3 sm:grid-cols-2">
            {props.inputs.map((input) => (
              <label key={input.id} className="block text-xs text-white/60">
                <span className="block mb-1 font-medium text-white/70">
                  {input.label}
                  {input.required && <span className="ml-1 text-rose-400">*</span>}
                </span>
                <input
                  type={input.type ?? "text"}
                  value={values[input.id] ?? ""}
                  onChange={(e) => setInput(input.id, e)}
                  placeholder={input.placeholder}
                  className="w-full rounded-xl border border-white/10 bg-black/30 px-3 py-2 text-sm text-white placeholder:text-white/25 focus:outline-none focus:ring-2 focus:ring-cyan-400/30"
                />
              </label>
            ))}
          </div>
        </div>
      )}

      <div className="mb-4 flex flex-col gap-3 rounded-[24px] border border-white/10 bg-[rgba(255,255,255,0.03)] p-4 sm:flex-row sm:items-center sm:justify-between">
        <div className="flex items-center gap-3">
          <span className="text-xs font-medium text-white/60">
            Progress {checkedCount}/{allItems.length}
          </span>
          <span className="block w-40 h-1.5 rounded-full bg-white/10 overflow-hidden">
            <span
              className="block h-full rounded-full bg-gradient-to-r from-cyan-400 to-blue-500 transition-all duration-300"
              style={{ width: `${pct}%` }}
            />
          </span>
        </div>
        <div className="flex flex-wrap items-center gap-2">
          <button
            type="button"
            onClick={() => checkAll(true)}
            className="px-3 py-1.5 rounded-lg text-xs font-medium text-white/70 hover:text-white border border-white/10 hover:border-white/30 transition-colors"
          >
            Check all
          </button>
          <button
            type="button"
            onClick={() => checkAll(false)}
            className="px-3 py-1.5 rounded-lg text-xs font-medium text-white/70 hover:text-white border border-white/10 hover:border-white/30 transition-colors"
          >
            Reset
          </button>
          <button
            type="button"
            onClick={copy}
            className="px-3 py-1.5 rounded-lg text-xs font-semibold text-white bg-cyan-500/90 hover:bg-cyan-400 transition-colors"
          >
            {copied ? "Copied!" : "Copy checklist"}
          </button>
          <button
            type="button"
            onClick={downloadMarkdown}
            className="px-3 py-1.5 rounded-lg text-xs font-semibold text-white/80 hover:text-white border border-white/10 hover:border-white/30 transition-colors"
          >
            Download .md
          </button>
        </div>
      </div>

      <div className="space-y-4">
        {props.sections.map((section) => (
          <div
            key={section.title}
            className="rounded-[24px] border border-white/10 bg-[rgba(255,255,255,0.03)] p-5 backdrop-blur-xl"
          >
            <div className="mb-3">
              <h2 className="text-base font-semibold text-white">{section.title}</h2>
              {section.description && (
                <p className="mt-1 text-xs text-white/55 leading-relaxed">{section.description}</p>
              )}
            </div>
            <ul className="space-y-2">
              {section.items.map((item) => {
                const checked = !!checks[item.id];
                return (
                  <li
                    key={item.id}
                    className="flex gap-3 rounded-xl border border-white/5 bg-black/20 px-3 py-2.5 hover:border-white/15 transition-colors"
                  >
                    <input
                      id={`chk-${item.id}`}
                      type="checkbox"
                      checked={checked}
                      onChange={() => toggle(item.id)}
                      className="mt-1 h-4 w-4 shrink-0 rounded border-white/20 bg-black/40 text-cyan-500 focus:ring-cyan-400/30"
                    />
                    <label htmlFor={`chk-${item.id}`} className="flex-1 cursor-pointer select-none">
                      <span
                        className={`block text-sm leading-6 transition-colors ${
                          checked ? "text-white/40 line-through" : "text-white/85"
                        }`}
                      >
                        {item.label}
                      </span>
                      {item.hint && (
                        <span className="block mt-0.5 text-xs text-white/45 leading-5">{item.hint}</span>
                      )}
                    </label>
                  </li>
                );
              })}
            </ul>
          </div>
        ))}
      </div>

      <div className="mt-6 rounded-[24px] border border-white/10 bg-black/30 p-4">
        <div className="flex items-center justify-between mb-2">
          <p className="text-[11px] font-semibold uppercase tracking-[0.28em] text-white/45">
            Checklist output (Markdown)
          </p>
          <span className="text-[11px] text-amber-300/80">Demo result · safe to copy/share</span>
        </div>
        <pre className="max-h-72 overflow-auto rounded-xl bg-black/40 p-3 text-xs leading-6 text-white/75 whitespace-pre-wrap">
{output}
        </pre>
      </div>
    </ToolPageLayout>
  );
}

function ChecklistMeta({ skill, why, futureApi }: { skill?: string; why?: string; futureApi?: string }) {
  if (!skill && !why && !futureApi) return null;
  return (
    <div className="mb-6 grid gap-3 sm:grid-cols-3">
      {skill && <MetaCard label="Skill demonstrated" body={skill} accent="cyan" />}
      {why && <MetaCard label="Why it's useful" body={why} accent="violet" />}
      {futureApi && <MetaCard label="Future API hook" body={futureApi} accent="emerald" />}
    </div>
  );
}

function MetaCard({
  label,
  body,
  accent,
}: {
  label: string;
  body: ReactNode;
  accent: "cyan" | "violet" | "emerald";
}) {
  const map: Record<string, string> = {
    cyan: "border-cyan-400/20 bg-cyan-500/5 text-cyan-200",
    violet: "border-violet-400/20 bg-violet-500/5 text-violet-200",
    emerald: "border-emerald-400/20 bg-emerald-500/5 text-emerald-200",
  };
  return (
    <div className={`rounded-2xl border p-4 ${map[accent]}`}>
      <p className="text-[10px] font-semibold uppercase tracking-[0.28em] opacity-80">{label}</p>
      <p className="mt-1.5 text-xs leading-6 text-white/75">{body}</p>
    </div>
  );
}
