"use client";

import GeneratorTool from "@/app/components/tools/GeneratorTool";

const RISKS = [
  { value: "low", label: "Low — pre-approved / standard change" },
  { value: "medium", label: "Medium — normal change, CAB notified" },
  { value: "high", label: "High — major change, full CAB approval" },
  { value: "emergency", label: "Emergency — ECAB approval after the fact" },
];

const TYPES = [
  { value: "config", label: "Configuration change" },
  { value: "feature", label: "Feature / new functionality" },
  { value: "patch", label: "Patch / hotfix" },
  { value: "infra", label: "Infrastructure / network" },
  { value: "policy", label: "Policy / process" },
];

export default function ChangeRequestPage() {
  return (
    <GeneratorTool
      title="Change Request Template Generator"
      description="Produce a clean, CAB-ready change request from a short summary, risk level and rollback plan."
      skill="ITIL change management, release governance."
      why="A repeatable template is the difference between approved changes and Friday-night incidents."
      futureApi="Wire to ServiceNow Change API or Jira Service Management to create the change record directly."
      outputBadge="Demo template · adapt to your CAB conventions"
      inputs={[
        { id: "title", label: "Change title", placeholder: "Upgrade Azure SQL elastic pool to GP_S_Gen5_4", required: true, span: "full" },
        { id: "type", label: "Change type", type: "select", options: TYPES, defaultValue: "config" },
        { id: "risk", label: "Risk level", type: "select", options: RISKS, defaultValue: "medium" },
        { id: "summary", label: "Change summary", type: "textarea", placeholder: "What is changing and why?", span: "full", required: true },
        { id: "rollback", label: "Rollback plan", type: "textarea", placeholder: "How will you back out if it goes wrong?", span: "full", required: true },
        { id: "owner", label: "Implementer", placeholder: "Your name" },
        { id: "window", label: "Planned change window", placeholder: "Sat 02:00–04:00 UTC" },
      ]}
      generate={(v) => {
        if (!v.title || !v.summary || !v.rollback) return "";
        const riskLabel = RISKS.find((r) => r.value === v.risk)?.label ?? "Medium";
        const typeLabel = TYPES.find((t) => t.value === v.type)?.label ?? "Configuration change";
        const lines: string[] = [];
        lines.push(`# Change Request: ${v.title}`);
        lines.push("");
        lines.push(`**Type:** ${typeLabel}`);
        lines.push(`**Risk:** ${riskLabel}`);
        if (v.window) lines.push(`**Window:** ${v.window}`);
        if (v.owner) lines.push(`**Implementer:** ${v.owner}`);
        lines.push("");
        lines.push("## 1. Summary");
        lines.push(v.summary);
        lines.push("");
        lines.push("## 2. Justification");
        lines.push("- Business / technical reason for the change.");
        lines.push("- Linked ticket / problem record.");
        lines.push("");
        lines.push("## 3. Scope & impact");
        lines.push("- Systems affected:");
        lines.push("- Users affected:");
        lines.push("- Expected downtime:");
        lines.push("");
        lines.push("## 4. Implementation plan");
        lines.push("1. Pre-checks (config snapshot, current state captured).");
        lines.push("2. Apply change steps in order.");
        lines.push("3. Validate success criteria (see section 6).");
        lines.push("4. Monitor for the next 24h.");
        lines.push("");
        lines.push("## 5. Rollback plan");
        lines.push(v.rollback);
        lines.push("");
        lines.push("## 6. Success criteria");
        lines.push("- [ ] No regressions in monitored dashboards.");
        lines.push("- [ ] Functional smoke test passes.");
        lines.push("- [ ] No new alerts in the 1h window after the change.");
        lines.push("");
        lines.push("## 7. Approvals");
        lines.push("- [ ] Service owner");
        lines.push(`- [ ] ${v.risk === "high" || v.risk === "emergency" ? "Full CAB" : "Peer reviewer"}`);
        lines.push("- [ ] Security review (if data or auth path affected)");
        lines.push("");
        lines.push("## 8. Communication");
        lines.push("- [ ] Pre-change notice to affected users.");
        lines.push("- [ ] Post-change confirmation.");
        lines.push("- [ ] Status page entry (if customer-facing).");
        lines.push("");
        lines.push("---");
        lines.push("_Generated by SecureScope — paste into your CAB ticket and edit as needed._");
        return lines.join("\n");
      }}
    />
  );
}
