import type { DayToDayToolDefinition } from "./types";

const DEVICE_HANDOVER_ITEMS = [
  "Asset tag recorded",
  "Autopilot / MDM enrolment verified",
  "Disk encryption on and recovery escrowed",
  "Baseline apps installed",
  "Wi-Fi / certificates deployed",
  "User acceptance sign-off",
];

const IT_USER_ISSUE = [
  "Confirm user, device, and network (VPN / office / home)",
  "Reproduce with exact steps and timestamps",
  "Check service health dashboards / status pages",
  "Review recent changes (updates, policy, password)",
  "Collect screenshots or error codes",
  "Try known-good account on same device",
  "Escalate with evidence bundle if unresolved in SLA",
];

const PRINTER_TRIAGE = [
  "Cable / Wi-Fi / queue host reachable",
  "Driver version matches model + OS build",
  "Clear spooler / restart print spooler service",
  "Test direct IP print vs server queue",
  "Check authentication / PIN printing policies",
  "Firmware update available?",
  "Vendor support ticket opened with logs",
];

const INTERNET_TRIAGE = [
  "Link light / speed negotiation on NIC",
  "DNS override test (1.1.1.1 / 8.8.8.8)",
  "Traceroute / path MTU hints",
  "Corporate proxy / PAC file changes",
  "Split tunnel vs full tunnel VPN behaviour",
  "ISP outage matrix / neighbour control test",
  "Document public IP and NAT path",
];

const OUTLOOK_TRIAGE = [
  "Online vs desktop client scope",
  "Profile repair / new Outlook toggle state",
  "Cached mode vs online mode test",
  "Add-in safe mode / disable third-party add-ins",
  "OST/PST integrity scan",
  "Autodiscover / SCP / OAuth prompt checks",
  "Mobile sync separation (Focus / Quiet hours)",
];

const TEAMS_TRIAGE = [
  "Web client vs desktop isolation test",
  "Clear Teams cache (per vendor guidance)",
  "Media stack reset (devices permissions)",
  "Policy: external access / meeting join rules",
  "TAC quality diagnostics export",
  "Sign out all / re-sign-in with MFA",
  "Escalate with HAR + call IDs if persistent",
];

const ONEDRIVE_TRIAGE = [
  "Known Folder Move conflicts",
  "Files On-Demand vs always available",
  "Reset OneDrive client with backup plan",
  "Path length / illegal characters scan",
  "SharePoint library sync scope review",
  "Antivirus exclusions for sync engine",
  "Telemetry upload for Microsoft support",
];

const BROWSER_CACHE_GUIDE = [
  "Close all tabs for the target profile",
  "Clear cached images and files (time range: All time)",
  "Preserve passwords/cookies if required by policy",
  "Hard refresh (⌘⇧R / Ctrl+F5) after clear",
  "Disable extensions temporarily to retest",
  "Try InPrivate / Incognito baseline",
  "Document version + build for ticket",
];

const M365_NEW_USER = [
  "UPN + primary SMTP aligned with naming standard",
  "Licence group membership applied (dynamic vs static)",
  "Teams + SharePoint sites provisioned",
  "OneDrive provision trigger / first sign-in",
  "Welcome mail / first-run checklist sent",
  "Manager delegated access where appropriate",
  "Security defaults / CA exclusions reviewed",
];

const M365_LEAVER = [
  "Convert mailbox → shared + delegate / litigation hold",
  "Remove group memberships and Teams ownership",
  "Revoke refresh tokens / sign-out everywhere",
  "Reclaim licences to pool / cost centre",
  "Device retire / wipe via Intune",
  "Data export / HRIS confirmation",
  "Access review task closed with evidence",
];

const SHARED_MBX = [
  "Purpose + data classification recorded",
  "Owners (2+) and backup approver identified",
  "Send As / Send on behalf decision",
  "Retention label / litigation hold decision",
  "Automapping vs explicit profile guidance documented",
  "Calendar permissions model agreed",
  "Decommission criteria captured",
];

const MFA_RESET = [
  "Strong caller verification completed",
  "Temporary access pass / break-glass if policy allows",
  "Authenticator rebind + backup codes reissued",
  "FIDO2 / Windows Hello re-enrolment scheduled",
  "Risky sign-in review after reset",
  "Ticket evidence stored per security policy",
];

const PWD_RESET = [
  "Identity proofing steps followed",
  "Self-service vs admin-initiated path chosen",
  "Temporary password forces change on login",
  "Password writeback health checked (hybrid)",
  "Smart lockout / risk policies observed post-reset",
  "User notified via out-of-band channel",
];

const TEAMS_PHONE = [
  "Emergency calling address validated",
  "Direct Routing SBC health pairs green",
  "Dial plan + voice routing policy assigned",
  "Resource accounts for call queues / auto attendants",
  "Survivable branch appliance (if applicable) tested",
  "QoS markings on LAN/WLAN verified",
  "PSTN usage reports baseline captured",
];

const INTUNE_ENROL = [
  "Enrollment restrictions scoped",
  "ESP profile assignments validated",
  "Compliance policy baseline applied",
  "Certificate profiles deployed",
  "Autopilot profile tagged to device group",
  "Company Portal branding + helpdesk contacts",
  "Pilot ring sign-off before broad deploy",
];

const BITLOCKER_RECOVERY = [
  "Recovery key retrieved from Entra / MBAM",
  "User identity verified before disclosure",
  "Key rotation scheduled if compromise suspected",
  "Suspend BitLocker before firmware updates (policy)",
  "Re-enable protection + escrow confirmation",
  "Incident ticket cross-linked to asset record",
];

const CYBER_PHISHING = [
  "Headers preserved (.eml) with chain intact",
  "URLs defanged for analysis notes",
  "User actions: clicked / creds entered / attachment opened",
  "IOC extraction (domains, IPs, hashes)",
  "Safe links / ATP detonation results captured",
  "Comms to user + retraining flag if needed",
  "Retention / legal hold guidance followed",
];

const PORT_BLOCK = [
  "Change ticket linked to CAB reference",
  "Hosts + directionality (inbound/outbound) explicit",
  "Default deny posture preserved",
  "Temporary vs permanent rule classification",
  "Rollback command / template attached",
  "Monitoring alert tuned for false positives",
  "Post-change validation window scheduled",
];

const ACCESS_REVIEW = [
  "Scope: apps, groups, roles defined",
  "Owners assigned with deadline",
  "Evidence export archived",
  "Remediation tasks created for rejects",
  "Privileged roles double-reviewed",
  "Exception process documented with expiry",
  "Leadership summary circulated",
];

const PRIV_ADMIN = [
  "Separate admin account from daily mailbox",
  "MFA strongest method enforced (FIDO preferred)",
  "Just-in-time elevation if available",
  "Dedicated workstation or PAW policy",
  "Sign-in risk policies applied to admin accounts",
  "Break-glass monitored with alerting",
  "Quarterly access validation complete",
];

const CYBER_HYGIENE = [
  "Disk encryption on for all mobile devices",
  "Automatic updates enabled + deferral sane",
  "Screen lock ≤ 5 minutes on portable systems",
  "Unique passwords + vault adoption",
  "Phish-resistant MFA on high-value accounts",
  "Backups tested restore monthly",
  "Least privilege on SaaS integrations",
];

const SEO_CHECKLIST = [
  "Title + meta description unique per page",
  "Canonical tags correct for parameterized URLs",
  "robots.txt allows strategic crawling",
  "XML sitemap submitted + fresh",
  "Structured data validates without errors",
  "Internal linking depth reasonable",
  "Core Web Vitals field data reviewed",
];

const LP_REVIEW = [
  "Above-the-fold CTA visible on mobile",
  "Headline matches campaign promise",
  "Social proof authentic and current",
  "Form friction vs value balanced",
  "Consent + privacy links prominent",
  "Thank-you page fires conversion pixel",
  "404 handling for offline campaigns",
];

const EMAIL_QA = [
  "Preheader complements subject (not duplicate)",
  "Alt text on hero imagery",
  "Plain-text part generated",
  "Link tracker domains allowlisted",
  "Seed inboxes across major ISPs",
  "Reply-to monitored during send window",
  "Pause / rollback owner identified",
];

const FORM_TEST = [
  "Field validation messages human-readable",
  "Double-submit protection verified",
  "File upload limits + AV scanning path",
  "Consent checkboxes not pre-ticked",
  "Thank-you + CRM sync success",
  "Error paths logged without leaking PII",
  "Mobile keyboard types appropriate",
];

const COOKIE_BANNER = [
  "Categories map to actual scripts loaded",
  "Default state respects jurisdiction",
  "Consent logged with timestamp + version",
  "Opt-down path works without dark patterns",
  "GTM / tag firing order respects consent",
  "Audit trail exportable",
  "Regression after each major release",
];

const A11Y_CHECK = [
  "Keyboard-only navigation path complete",
  "Focus order logical + visible ring",
  "Contrast AA on text + interactive states",
  "Landmarks + headings structured",
  "Live regions for async updates",
  "Media captions / transcripts where needed",
  "Automated scan + manual spot checks logged",
];

const MOBILE_RESP = [
  "Breakpoints tested on real devices",
  "Touch targets ≥ 44px where possible",
  "No horizontal scroll on primary flows",
  "Performance on 3G Fast profile acceptable",
  "Orientation changes preserve state",
  "Sticky nav does not obscure CTAs",
  "Safe-area insets respected (notch)",
];

const CONV_TRACKING = [
  "GA4 events mirror business outcomes",
  "Consent Mode defaults documented",
  "Cross-domain linker if multi-domain funnel",
  "Ads pixels deduplicated where applicable",
  "Server-side tagging risks reviewed",
  "QA hits visible in DebugView",
  "Rollback playbook for bad releases",
];

const REGRESSION = [
  "Smoke suite green on staging",
  "Critical auth paths covered",
  "Payments / booking flows included if applicable",
  "Email deliverability spot-check post-release",
  "404 rate anomaly alert configured",
  "Feature flags documented + owners",
  "Post-release monitoring window assigned",
];

const CALL_QUEUE = [
  "Music on hold + comfort message legal review",
  "Overflow / timeout targets configured",
  "Agent presence states tested",
  "Emergency / after-hours path validated",
  "Callback offer behaves as designed",
  "Reporting interval matches ops cadence",
  "Failover trunk tested with provider",
];

const LEAD_QUALITY = [
  "Source + medium captured consistently",
  "Required firmographics present for routing",
  "Spam / bot patterns filtered",
  "Consent evidence retained",
  "SLA for first touch documented",
  "Disqualification reasons coded",
  "Feedback loop to marketing weekly",
];

const CAMPAIGN_CHECK = [
  "Objective + KPI single-owner",
  "Audience exclusions applied (customers, employees)",
  "Creative variants linked to UTMs",
  "Budget pacing + bid caps set",
  "Frequency caps humane",
  "Learning phase disruption risks noted",
  "Launch + rollback comms drafted",
];

export const EXPANDED_DAY_TO_DAY_TOOLS_A: DayToDayToolDefinition[] = [
  {
    id: "personal-daily-dashboard",
    title: "Daily work dashboard",
    description: "Priorities, notes, checklists, meetings placeholder, due checks, and end-of-day report — all saved locally.",
    categoryId: "dashboard",
    keywords: ["dashboard", "daily", "summary", "tasks"],
    labels: ["most-used", "recently-added"],
    panel: { kind: "dailyDashboard", storageKey: "ss_d2d_daily_dashboard_bundle" },
  },
  // IT Support Toolkit
  {
    id: "it-ticket-note-generator",
    title: "IT ticket note generator",
    description: "Structured notes for helpdesk systems.",
    categoryId: "it-support",
    keywords: ["ticket", "helpdesk", "notes"],
    labels: ["recently-added"],
    panel: { kind: "generator", templateId: "it-ticket-notes" },
  },
  {
    id: "user-issue-troubleshooting-checklist",
    title: "User issue troubleshooting checklist",
    description: "First-line triage gates before escalation.",
    categoryId: "it-support",
    keywords: ["triage", "tier 1", "support"],
    labels: ["recently-added"],
    panel: { kind: "staticChecklist", items: IT_USER_ISSUE },
  },
  {
    id: "device-handover-checklist-it",
    title: "Device handover checklist",
    description: "Receiving or issuing hardware with audit trail.",
    categoryId: "it-support",
    keywords: ["handover", "asset", "laptop"],
    labels: ["recently-added"],
    panel: { kind: "staticChecklist", items: DEVICE_HANDOVER_ITEMS },
  },
  {
    id: "laptop-setup-tracker",
    title: "Laptop setup tracker",
    description: "Row-based tracker for builds and milestones.",
    categoryId: "it-support",
    keywords: ["imaging", "autopilot", "build"],
    labels: ["recently-added"],
    panel: {
      kind: "rowLog",
      storageKey: "ss_d2d_laptop_setup_rows",
      columns: [
        { id: "machine", label: "Machine" },
        { id: "stage", label: "Stage" },
        { id: "owner", label: "Engineer" },
        { id: "notes", label: "Notes" },
      ],
    },
  },
  {
    id: "printer-troubleshooting-checklist",
    title: "Printer troubleshooting checklist",
    description: "Spooler, drivers, and queue checks.",
    categoryId: "it-support",
    keywords: ["printer", "spooler", "queue"],
    labels: ["recently-added"],
    panel: { kind: "staticChecklist", items: PRINTER_TRIAGE },
  },
  {
    id: "internet-issue-checklist",
    title: "Internet issue checklist",
    description: "Connectivity path isolation.",
    categoryId: "it-support",
    keywords: ["wifi", "dns", "vpn"],
    labels: ["recently-added"],
    panel: { kind: "staticChecklist", items: INTERNET_TRIAGE },
  },
  {
    id: "outlook-issue-checklist",
    title: "Outlook issue checklist",
    description: "Desktop + web parity tests.",
    categoryId: "it-support",
    keywords: ["outlook", "exchange", "cache"],
    labels: ["recently-added"],
    panel: { kind: "staticChecklist", items: OUTLOOK_TRIAGE },
  },
  {
    id: "teams-issue-checklist",
    title: "Microsoft Teams issue checklist",
    description: "Media, cache, and policy isolation.",
    categoryId: "it-support",
    keywords: ["teams", "av", "cache"],
    labels: ["recently-added"],
    panel: { kind: "staticChecklist", items: TEAMS_TRIAGE },
  },
  {
    id: "onedrive-sync-issue-checklist",
    title: "OneDrive sync issue checklist",
    description: "Sync engine, path, and policy checks.",
    categoryId: "it-support",
    keywords: ["onedrive", "sync", "sharepoint"],
    labels: ["recently-added"],
    panel: { kind: "staticChecklist", items: ONEDRIVE_TRIAGE },
  },
  {
    id: "browser-cache-clearing-guide",
    title: "Browser cache clearing guide",
    description: "Safe sequence for major browsers.",
    categoryId: "it-support",
    keywords: ["cache", "browser", "cookies"],
    labels: ["recently-added"],
    panel: { kind: "staticChecklist", items: BROWSER_CACHE_GUIDE },
  },
  {
    id: "windows-quick-commands-reference",
    title: "Windows quick commands reference",
    description: "Non-exhaustive cheat sheet for deskside support.",
    categoryId: "it-support",
    keywords: ["powershell", "cmd", "windows"],
    labels: ["recently-added"],
    panel: { kind: "commandReference", variant: "windows" },
  },
  {
    id: "mac-quick-commands-reference",
    title: "Mac quick commands reference",
    description: "Terminal snippets for support scenarios.",
    categoryId: "it-support",
    keywords: ["macos", "terminal", "zsh"],
    labels: ["recently-added"],
    panel: { kind: "commandReference", variant: "mac" },
  },
  {
    id: "remote-support-session-log",
    title: "Remote support session log",
    description: "Track screen-share sessions with outcomes.",
    categoryId: "it-support",
    keywords: ["remote", "bomgar", "quick assist"],
    labels: ["recently-added"],
    panel: {
      kind: "rowLog",
      storageKey: "ss_d2d_remote_sessions",
      columns: [
        { id: "when", label: "When" },
        { id: "user", label: "User" },
        { id: "tool", label: "Tool" },
        { id: "outcome", label: "Outcome" },
      ],
    },
  },
  {
    id: "asset-handover-form-generator",
    title: "Asset handover form",
    description: "Generate a handover block for tickets or PDFs.",
    categoryId: "it-support",
    keywords: ["handover", "asset tag", "signature"],
    labels: ["recently-added"],
    panel: { kind: "generator", templateId: "asset-handover" },
  },
  {
    id: "software-install-request-form",
    title: "Software install request form",
    description: "Structured request you can paste into ITSM.",
    categoryId: "it-support",
    keywords: ["software", "request", "itsm"],
    labels: ["recently-added"],
    panel: { kind: "generator", templateId: "software-install-request" },
  },
  // Microsoft 365 Admin Toolkit
  {
    id: "m365-new-user-setup-checklist",
    title: "New user setup checklist",
    description: "Lifecycle checklist tuned for Microsoft 365.",
    categoryId: "m365-admin",
    keywords: ["onboarding", "entra", "mailbox"],
    labels: ["recently-added"],
    panel: { kind: "staticChecklist", items: M365_NEW_USER },
  },
  {
    id: "m365-leaver-process-checklist",
    title: "Leaver process checklist",
    description: "Offboarding tasks with tenant hygiene focus.",
    categoryId: "m365-admin",
    keywords: ["offboarding", "leaver", "litigation hold"],
    labels: ["recently-added"],
    panel: { kind: "staticChecklist", items: M365_LEAVER },
  },
  {
    id: "shared-mailbox-setup-checklist",
    title: "Shared mailbox setup checklist",
    description: "Ownership, permissions, and lifecycle.",
    categoryId: "m365-admin",
    keywords: ["shared mailbox", "exchange"],
    labels: ["recently-added"],
    panel: { kind: "staticChecklist", items: SHARED_MBX },
  },
  {
    id: "distribution-list-request-form",
    title: "Distribution list request form",
    description: "Generate a DL / group request snippet.",
    categoryId: "m365-admin",
    keywords: ["distribution list", "group", "exchange"],
    labels: ["recently-added"],
    panel: { kind: "generator", templateId: "distribution-list-request" },
  },
  {
    id: "licence-request-tracker",
    title: "Licence request tracker",
    description: "Track SKU requests and approvals locally.",
    categoryId: "m365-admin",
    keywords: ["licence", "sku", "approval"],
    labels: ["recently-added"],
    panel: {
      kind: "rowLog",
      storageKey: "ss_d2d_licence_requests",
      columns: [
        { id: "user", label: "User" },
        { id: "sku", label: "Requested SKU" },
        { id: "status", label: "Status" },
        { id: "notes", label: "Approver notes" },
      ],
    },
  },
  {
    id: "mfa-reset-checklist",
    title: "MFA reset checklist",
    description: "Verifier steps and risk follow-up.",
    categoryId: "m365-admin",
    keywords: ["mfa", "reset", "authenticator"],
    labels: ["recently-added"],
    panel: { kind: "staticChecklist", items: MFA_RESET },
  },
  {
    id: "password-reset-checklist",
    title: "Password reset checklist",
    description: "Identity proofing and hybrid notes.",
    categoryId: "m365-admin",
    keywords: ["password", "reset", "writeback"],
    labels: ["recently-added"],
    panel: { kind: "staticChecklist", items: PWD_RESET },
  },
  {
    id: "conditional-access-policy-notes",
    title: "Conditional Access policy notes",
    description: "Scratchpad for named locations, exclusions, and what-if results.",
    categoryId: "m365-admin",
    keywords: ["conditional access", "named locations"],
    labels: ["recently-added"],
    panel: { kind: "notes", storageKey: "ss_d2d_ca_notes", placeholder: "## Policy\n## Signals\n## Exclusions\n## What-if notes\n" },
  },
  {
    id: "exchange-message-trace-notes",
    title: "Exchange message trace notes",
    description: "Capture trace IDs, timelines, and hypotheses.",
    categoryId: "m365-admin",
    keywords: ["message trace", "exchange", "headers"],
    labels: ["recently-added"],
    panel: { kind: "notes", storageKey: "ss_d2d_msg_trace", placeholder: "## Message ID\n## Timeline\n## Hypothesis\n## Next steps\n" },
  },
  {
    id: "teams-phone-setup-checklist",
    title: "Teams Phone setup checklist",
    description: "PSTN + routing validation gates.",
    categoryId: "m365-admin",
    keywords: ["teams phone", "pstn", "sbc"],
    labels: ["recently-added", "automation-ready"],
    panel: { kind: "staticChecklist", items: TEAMS_PHONE },
  },
  {
    id: "intune-device-enrolment-checklist",
    title: "Intune device enrolment checklist",
    description: "Pilot to broad deployment checks.",
    categoryId: "m365-admin",
    keywords: ["intune", "enrolment", "esp"],
    labels: ["recently-added"],
    panel: { kind: "staticChecklist", items: INTUNE_ENROL },
  },
  {
    id: "defender-security-check-log",
    title: "Defender security check log",
    description: "Row log for TVM / AV findings follow-up.",
    categoryId: "m365-admin",
    keywords: ["defender", "tvm", "asr"],
    labels: ["recently-added", "automation-ready"],
    panel: {
      kind: "rowLog",
      storageKey: "ss_d2d_defender_checks",
      columns: [
        { id: "device", label: "Device" },
        { id: "finding", label: "Finding" },
        { id: "severity", label: "Severity" },
        { id: "owner", label: "Owner" },
      ],
    },
  },
  {
    id: "bitlocker-recovery-key-checklist",
    title: "BitLocker recovery key checklist",
    description: "Recovery operations with audit alignment.",
    categoryId: "m365-admin",
    keywords: ["bitlocker", "recovery key", "escrow"],
    labels: ["recently-added"],
    panel: { kind: "staticChecklist", items: BITLOCKER_RECOVERY },
  },
  {
    id: "admin-change-log",
    title: "Admin change log",
    description: "Who changed what in the tenant (manual log until SIEM wiring).",
    categoryId: "m365-admin",
    keywords: ["change log", "tenant", "audit"],
    labels: ["recently-added"],
    panel: {
      kind: "rowLog",
      storageKey: "ss_d2d_admin_changes",
      columns: [
        { id: "when", label: "When" },
        { id: "actor", label: "Actor" },
        { id: "change", label: "Change" },
        { id: "risk", label: "Risk / rollback" },
      ],
    },
  },
  {
    id: "m365-audit-notes-template",
    title: "Microsoft 365 audit notes template",
    description: "Free-form audit prep with export.",
    categoryId: "m365-admin",
    keywords: ["audit", "evidence", "compliance"],
    labels: ["recently-added"],
    panel: { kind: "notes", storageKey: "ss_d2d_m365_audit", placeholder: "## Scope\n## Evidence pulled\n## Findings\n## Remediation owners\n" },
  },
  // Cybersecurity Toolkit
  {
    id: "incident-report-generator",
    title: "Incident report generator",
    description: "Initial IR narrative scaffold.",
    categoryId: "cyber",
    keywords: ["incident", "ir", "sev"],
    labels: ["recently-added"],
    panel: { kind: "generator", templateId: "incident-report" },
  },
  {
    id: "phishing-email-review-checklist",
    title: "Phishing email review checklist",
    description: "Safe handling and evidence capture.",
    categoryId: "cyber",
    keywords: ["phishing", "headers", "ioc"],
    labels: ["recently-added"],
    panel: { kind: "staticChecklist", items: CYBER_PHISHING },
  },
  {
    id: "suspicious-link-notes",
    title: "Suspicious link notes",
    description: "Defanged URLs + analyst notes.",
    categoryId: "cyber",
    keywords: ["url", "malware", "analysis"],
    labels: ["recently-added"],
    panel: { kind: "notes", storageKey: "ss_d2d_suspicious_links", placeholder: "## Defanged URL\n## Redirect chain\n## Sandbox notes\n" },
  },
  {
    id: "malware-scan-log",
    title: "Malware scan log",
    description: "Endpoints, engines, and outcomes.",
    categoryId: "cyber",
    keywords: ["malware", "scan", "defender"],
    labels: ["recently-added"],
    panel: {
      kind: "rowLog",
      storageKey: "ss_d2d_malware_scans",
      columns: [
        { id: "asset", label: "Asset" },
        { id: "engine", label: "Engine" },
        { id: "result", label: "Result" },
        { id: "notes", label: "Notes" },
      ],
    },
  },
  {
    id: "firewall-rule-change-log",
    title: "Firewall rule change log",
    description: "Track approvals and validations.",
    categoryId: "cyber",
    keywords: ["firewall", "change", "cisco", "palo"],
    labels: ["recently-added"],
    panel: {
      kind: "rowLog",
      storageKey: "ss_d2d_fw_changes",
      columns: [
        { id: "ticket", label: "Ticket" },
        { id: "rule", label: "Rule summary" },
        { id: "engineer", label: "Engineer" },
        { id: "status", label: "Status" },
      ],
    },
  },
  {
    id: "port-blocking-checklist",
    title: "Port blocking checklist",
    description: "Host and perimeter alignment.",
    categoryId: "cyber",
    keywords: ["ports", "firewall", "hardening"],
    labels: ["recently-added"],
    panel: { kind: "staticChecklist", items: PORT_BLOCK },
  },
  {
    id: "security-awareness-notes",
    title: "Security awareness notes",
    description: "Campaign ideas, exceptions, and exec briefings.",
    categoryId: "cyber",
    keywords: ["awareness", "training", "phish sim"],
    labels: ["recently-added"],
    panel: { kind: "notes", storageKey: "ss_d2d_sec_aware", placeholder: "## Audiences\n## Cadence\n## Metrics\n## Exceptions\n" },
  },
  {
    id: "risk-register",
    title: "Risk register",
    description: "Lightweight risk rows with owners.",
    categoryId: "cyber",
    keywords: ["risk", "register", "treatment"],
    labels: ["recently-added"],
    panel: {
      kind: "rowLog",
      storageKey: "ss_d2d_risk_register",
      columns: [
        { id: "risk", label: "Risk" },
        { id: "score", label: "Score" },
        { id: "owner", label: "Owner" },
        { id: "treatment", label: "Treatment" },
      ],
    },
  },
  {
    id: "vulnerability-notes-tracker",
    title: "Vulnerability notes tracker",
    description: "Track CVE findings and compensating controls.",
    categoryId: "cyber",
    keywords: ["cve", "vulnerability", "patch"],
    labels: ["recently-added", "automation-ready"],
    panel: {
      kind: "rowLog",
      storageKey: "ss_d2d_vuln_tracker",
      columns: [
        { id: "cve", label: "CVE / finding" },
        { id: "asset", label: "Asset" },
        { id: "severity", label: "Severity" },
        { id: "eta", label: "ETA" },
      ],
    },
  },
  {
    id: "patch-management-tracker",
    title: "Patch management tracker",
    description: "Wave planning with sign-off notes.",
    categoryId: "cyber",
    keywords: ["patch", "wsus", "intune"],
    labels: ["recently-added", "automation-ready"],
    panel: {
      kind: "rowLog",
      storageKey: "ss_d2d_patch_waves",
      columns: [
        { id: "wave", label: "Wave" },
        { id: "scope", label: "Scope" },
        { id: "date", label: "Planned date" },
        { id: "result", label: "Result" },
      ],
    },
  },
  {
    id: "backup-check-log",
    title: "Backup check log",
    description: "Jobs, RPO/RTO notes, and exceptions.",
    categoryId: "cyber",
    keywords: ["backup", "rpo", "rto"],
    labels: ["recently-added"],
    panel: {
      kind: "rowLog",
      storageKey: "ss_d2d_backup_checks",
      columns: [
        { id: "system", label: "System" },
        { id: "job", label: "Job" },
        { id: "status", label: "Status" },
        { id: "notes", label: "Notes" },
      ],
    },
  },
  {
    id: "access-review-checklist",
    title: "Access review checklist",
    description: "Structured access review cadence.",
    categoryId: "cyber",
    keywords: ["access review", "iam", "governance"],
    labels: ["recently-added"],
    panel: { kind: "staticChecklist", items: ACCESS_REVIEW },
  },
  {
    id: "privileged-admin-account-checklist",
    title: "Privileged admin account checklist",
    description: "Hardening pattern for break-glass adjacent accounts.",
    categoryId: "cyber",
    keywords: ["privileged", "admin", "paw"],
    labels: ["recently-added"],
    panel: { kind: "staticChecklist", items: PRIV_ADMIN },
  },
  {
    id: "security-improvement-backlog",
    title: "Security improvement backlog",
    description: "Prioritised improvements with impact notes.",
    categoryId: "cyber",
    keywords: ["backlog", "remediation", "ciso"],
    labels: ["recently-added"],
    panel: {
      kind: "rowLog",
      storageKey: "ss_d2d_sec_backlog",
      columns: [
        { id: "item", label: "Item" },
        { id: "impact", label: "Impact" },
        { id: "effort", label: "Effort" },
        { id: "owner", label: "Owner" },
      ],
    },
  },
  {
    id: "cyber-hygiene-checklist",
    title: "Cyber hygiene checklist",
    description: "Baseline personal + endpoint hygiene.",
    categoryId: "cyber",
    keywords: ["hygiene", "endpoint", "basics"],
    labels: ["recently-added"],
    panel: { kind: "staticChecklist", items: CYBER_HYGIENE },
  },
  // Marketing Operations Toolkit
  {
    id: "daily-marketing-checks-dashboard",
    title: "Daily marketing checks dashboard",
    description: "Channel checks with status columns.",
    categoryId: "marketing-ops",
    keywords: ["marketing ops", "checks", "dashboard"],
    labels: ["recently-added"],
    panel: {
      kind: "rowLog",
      storageKey: "ss_d2d_mkt_ops_daily",
      columns: [
        { id: "channel", label: "Channel" },
        { id: "check", label: "Check" },
        { id: "status", label: "Status" },
        { id: "owner", label: "Owner" },
      ],
    },
  },
  {
    id: "lead-source-tracker-marketing-ops",
    title: "Lead source tracker",
    description: "Marketing ops view with quality hints.",
    categoryId: "marketing-ops",
    keywords: ["lead source", "attribution"],
    labels: ["recently-added"],
    panel: {
      kind: "rowLog",
      storageKey: "ss_d2d_mkt_ops_sources",
      columns: [
        { id: "source", label: "Source" },
        { id: "volume", label: "Volume" },
        { id: "quality", label: "Quality" },
        { id: "notes", label: "Notes" },
      ],
    },
  },
  {
    id: "lead-quality-checklist",
    title: "Lead quality checklist",
    description: "Standardise MQL / SQL acceptance.",
    categoryId: "marketing-ops",
    keywords: ["mql", "sql", "quality"],
    labels: ["recently-added"],
    panel: { kind: "staticChecklist", items: LEAD_QUALITY },
  },
  {
    id: "campaign-checklist-marketing-ops",
    title: "Campaign checklist",
    description: "Launch readiness for paid / lifecycle sends.",
    categoryId: "marketing-ops",
    keywords: ["campaign", "launch", "qa"],
    labels: ["recently-added"],
    panel: { kind: "staticChecklist", items: CAMPAIGN_CHECK },
  },
  {
    id: "campaign-brief-generator",
    title: "Campaign brief generator",
    description: "Structured brief for agencies or internal teams.",
    categoryId: "marketing-ops",
    keywords: ["brief", "creative", "objective"],
    labels: ["recently-added"],
    panel: { kind: "generator", templateId: "campaign-brief" },
  },
  {
    id: "social-media-content-planner",
    title: "Social media content planner",
    description: "Weekly grid notes with export.",
    categoryId: "marketing-ops",
    keywords: ["social", "calendar", "content"],
    labels: ["recently-added"],
    panel: { kind: "notes", storageKey: "ss_d2d_social_plan", placeholder: "## Week of\n| Day | Channel | Hook | CTA | Status |\n| --- | --- | --- | --- | --- |\n" },
  },
  {
    id: "blog-outline-generator",
    title: "Blog outline generator",
    description: "Outline scaffold from topic + audience.",
    categoryId: "marketing-ops",
    keywords: ["blog", "outline", "seo"],
    labels: ["recently-added"],
    panel: { kind: "generator", templateId: "blog-outline" },
  },
  {
    id: "seo-checklist-marketing-ops",
    title: "SEO checklist",
    description: "On-page + technical essentials.",
    categoryId: "marketing-ops",
    keywords: ["seo", "technical", "content"],
    labels: ["recently-added"],
    panel: { kind: "staticChecklist", items: SEO_CHECKLIST },
  },
  {
    id: "landing-page-review-checklist",
    title: "Landing page review checklist",
    description: "CRO-oriented QA list.",
    categoryId: "marketing-ops",
    keywords: ["landing page", "cro", "conversion"],
    labels: ["recently-added"],
    panel: { kind: "staticChecklist", items: LP_REVIEW },
  },
  {
    id: "email-campaign-qa-checklist",
    title: "Email campaign QA checklist",
    description: "Pre-flight checks for lifecycle + broadcast.",
    categoryId: "marketing-ops",
    keywords: ["email", "esp", "qa"],
    labels: ["recently-added"],
    panel: { kind: "staticChecklist", items: EMAIL_QA },
  },
  {
    id: "utm-campaign-builder-marketing-ops",
    title: "UTM campaign builder",
    description: "Same local builder as core marketing tools — duplicated for ops workflows.",
    categoryId: "marketing-ops",
    keywords: ["utm", "ga4", "campaign"],
    labels: ["most-used", "recently-added"],
    panel: { kind: "utmBuilder" },
  },
  {
    id: "ab-testing-tracker",
    title: "A/B testing tracker",
    description: "Experiments with hypothesis and readout fields.",
    categoryId: "marketing-ops",
    keywords: ["ab test", "experiment", "variant"],
    labels: ["recently-added"],
    panel: {
      kind: "rowLog",
      storageKey: "ss_d2d_ab_tracker",
      columns: [
        { id: "name", label: "Experiment" },
        { id: "hypothesis", label: "Hypothesis" },
        { id: "metric", label: "Primary metric" },
        { id: "result", label: "Result" },
      ],
    },
  },
  {
    id: "competitor-notes-tracker",
    title: "Competitor notes tracker",
    description: "Positioning, pricing signals, and campaigns.",
    categoryId: "marketing-ops",
    keywords: ["competitor", "intel", "pricing"],
    labels: ["recently-added"],
    panel: {
      kind: "rowLog",
      storageKey: "ss_d2d_competitors",
      columns: [
        { id: "competitor", label: "Competitor" },
        { id: "signal", label: "Signal" },
        { id: "impact", label: "Impact" },
        { id: "source", label: "Source" },
      ],
    },
  },
  {
    id: "website-form-test-log",
    title: "Website form test log",
    description: "Capture passes per form with evidence links.",
    categoryId: "marketing-ops",
    keywords: ["form", "crm", "lead"],
    labels: ["recently-added", "automation-ready"],
    panel: {
      kind: "rowLog",
      storageKey: "ss_d2d_form_tests_mkt",
      columns: [
        { id: "form", label: "Form" },
        { id: "case", label: "Test case" },
        { id: "status", label: "Status" },
        { id: "link", label: "Evidence link" },
      ],
    },
  },
  {
    id: "live-chat-test-log",
    title: "Live chat test log",
    description: "Queue behaviour and SLA notes.",
    categoryId: "marketing-ops",
    keywords: ["chat", "cx", "queue"],
    labels: ["recently-added"],
    panel: {
      kind: "rowLog",
      storageKey: "ss_d2d_chat_tests",
      columns: [
        { id: "scenario", label: "Scenario" },
        { id: "agent", label: "Agent" },
        { id: "latency", label: "Latency" },
        { id: "notes", label: "Notes" },
      ],
    },
  },
];
