import type { DayToDayToolDefinition } from "./types";

export const EXPANDED_DAY_TO_DAY_TOOLS_B: DayToDayToolDefinition[] = [
  // Website Testing Toolkit
  {
    id: "form-test-checklist",
    title: "Form test checklist",
    description: "Structured passes for marketing and transactional forms.",
    categoryId: "website-testing",
    keywords: ["form", "validation", "crm"],
    labels: ["recently-added", "automation-ready"],
    panel: {
      kind: "staticChecklist",
      items: [
        "Field validation messages human-readable",
        "Double-submit protection verified",
        "File upload limits + AV scanning path",
        "Consent checkboxes not pre-ticked",
        "Thank-you + CRM sync success",
        "Error paths logged without leaking PII",
        "Mobile keyboard types appropriate",
      ],
    },
  },
  {
    id: "broken-link-checker-placeholder",
    title: "Broken link checker (placeholder)",
    description: "Reserved for server-side crawl — avoid unauthenticated bulk fetching from browsers.",
    categoryId: "website-testing",
    keywords: ["links", "crawl", "seo"],
    labels: ["recently-added", "automation-ready"],
    panel: { kind: "apiPlaceholder", scenario: "broken-links" },
  },
  {
    id: "page-speed-notes",
    title: "Page speed notes",
    description: "Lab vs field notes, LCP element, and third-party scripts.",
    categoryId: "website-testing",
    keywords: ["cwv", "lcp", "perf"],
    labels: ["recently-added"],
    panel: { kind: "notes", storageKey: "ss_d2d_page_speed", placeholder: "## URL\n## LCP element\n## Main thread blockers\n## Third parties\n" },
  },
  {
    id: "seo-metadata-checker-placeholder",
    title: "SEO metadata checker (placeholder)",
    description: "Future server fetch + parse — tokens stay off the client.",
    categoryId: "website-testing",
    keywords: ["meta", "canonical", "robots"],
    labels: ["recently-added", "automation-ready"],
    panel: { kind: "apiPlaceholder", scenario: "seo-meta" },
  },
  {
    id: "cookie-banner-checklist",
    title: "Cookie banner checklist",
    description: "Consent categories vs actual tags.",
    categoryId: "website-testing",
    keywords: ["consent", "gtm", "cmp"],
    labels: ["recently-added"],
    panel: {
      kind: "staticChecklist",
      items: [
        "Categories map to actual scripts loaded",
        "Default state respects jurisdiction",
        "Consent logged with timestamp + version",
        "Opt-down path works without dark patterns",
        "GTM / tag firing order respects consent",
        "Audit trail exportable",
        "Regression after each major release",
      ],
    },
  },
  {
    id: "accessibility-checklist",
    title: "Accessibility checklist",
    description: "Manual + automated coverage notes.",
    categoryId: "website-testing",
    keywords: ["a11y", "wcag", "keyboard"],
    labels: ["recently-added"],
    panel: {
      kind: "staticChecklist",
      items: [
        "Keyboard-only navigation path complete",
        "Focus order logical + visible ring",
        "Contrast AA on text + interactive states",
        "Landmarks + headings structured",
        "Live regions for async updates",
        "Media captions / transcripts where needed",
        "Automated scan + manual spot checks logged",
      ],
    },
  },
  {
    id: "mobile-responsiveness-checklist",
    title: "Mobile responsiveness checklist",
    description: "Layout and interaction checks on small viewports.",
    categoryId: "website-testing",
    keywords: ["mobile", "responsive", "viewport"],
    labels: ["recently-added"],
    panel: {
      kind: "staticChecklist",
      items: [
        "Breakpoints tested on real devices",
        "Touch targets ≥ 44px where possible",
        "No horizontal scroll on primary flows",
        "Performance on 3G Fast profile acceptable",
        "Orientation changes preserve state",
        "Sticky nav does not obscure CTAs",
        "Safe-area insets respected (notch)",
      ],
    },
  },
  {
    id: "contact-form-test-log",
    title: "Contact form test log",
    description: "Per-environment pass tracking.",
    categoryId: "website-testing",
    keywords: ["contact", "form", "smtp"],
    labels: ["recently-added"],
    panel: {
      kind: "rowLog",
      storageKey: "ss_d2d_contact_form_tests",
      columns: [
        { id: "env", label: "Environment" },
        { id: "case", label: "Case" },
        { id: "result", label: "Result" },
        { id: "notes", label: "Notes" },
      ],
    },
  },
  {
    id: "conversion-tracking-checklist",
    title: "Conversion tracking checklist",
    description: "Pixels, GA4, and consent alignment.",
    categoryId: "website-testing",
    keywords: ["ga4", "pixels", "consent mode"],
    labels: ["recently-added", "automation-ready"],
    panel: {
      kind: "staticChecklist",
      items: [
        "GA4 events mirror business outcomes",
        "Consent Mode defaults documented",
        "Cross-domain linker if multi-domain funnel",
        "Ads pixels deduplicated where applicable",
        "Server-side tagging risks reviewed",
        "QA hits visible in DebugView",
        "Rollback playbook for bad releases",
      ],
    },
  },
  {
    id: "analytics-check-log",
    title: "Analytics check log",
    description: "Property health checks and anomalies.",
    categoryId: "website-testing",
    keywords: ["analytics", "ga4", "anomaly"],
    labels: ["recently-added"],
    panel: {
      kind: "rowLog",
      storageKey: "ss_d2d_analytics_checks",
      columns: [
        { id: "property", label: "Property" },
        { id: "check", label: "Check" },
        { id: "status", label: "Status" },
        { id: "notes", label: "Notes" },
      ],
    },
  },
  {
    id: "screenshot-evidence-notes",
    title: "Screenshot evidence notes",
    description: "Links to evidence packs or filenames.",
    categoryId: "website-testing",
    keywords: ["screenshots", "evidence", "qa"],
    labels: ["recently-added"],
    panel: { kind: "notes", storageKey: "ss_d2d_screenshots", placeholder: "## Release\n## Folder / link\n## Key shots captured\n" },
  },
  {
    id: "regression-test-checklist",
    title: "Regression test checklist",
    description: "Release train sign-off list.",
    categoryId: "website-testing",
    keywords: ["regression", "release", "smoke"],
    labels: ["recently-added", "automation-ready"],
    panel: {
      kind: "staticChecklist",
      items: [
        "Smoke suite green on staging",
        "Critical auth paths covered",
        "Payments / booking flows included if applicable",
        "Email deliverability spot-check post-release",
        "404 rate anomaly alert configured",
        "Feature flags documented + owners",
        "Post-release monitoring window assigned",
      ],
    },
  },
  {
    id: "playwright-test-command-reference",
    title: "Playwright test command reference",
    description: "Common CLI patterns for local + CI.",
    categoryId: "website-testing",
    keywords: ["playwright", "e2e", "ci"],
    labels: ["recently-added", "automation-ready"],
    panel: { kind: "commandReference", variant: "playwright" },
  },
  {
    id: "test-results-export-panel",
    title: "Test results export panel",
    description: "Capture suite runs with export to JSON/CSV.",
    categoryId: "website-testing",
    keywords: ["export", "results", "qa"],
    labels: ["recently-added"],
    panel: {
      kind: "rowLog",
      storageKey: "ss_d2d_test_results_export",
      columns: [
        { id: "suite", label: "Suite" },
        { id: "when", label: "When" },
        { id: "pass", label: "Passed" },
        { id: "fail", label: "Failed" },
        { id: "notes", label: "Notes / link" },
      ],
    },
  },
  // Phone / Lead Testing Toolkit
  {
    id: "phone-test-log",
    title: "Phone test log",
    description: "Inbound/outbound test matrix.",
    categoryId: "phone-leads",
    keywords: ["pstn", "ivr", "test call"],
    labels: ["recently-added", "automation-ready"],
    panel: {
      kind: "rowLog",
      storageKey: "ss_d2d_phone_tests",
      columns: [
        { id: "number", label: "Number" },
        { id: "scenario", label: "Scenario" },
        { id: "result", label: "Result" },
        { id: "notes", label: "Notes" },
      ],
    },
  },
  {
    id: "callback-test-tracker",
    title: "Callback test tracker",
    description: "Promise vs actual callback timing.",
    categoryId: "phone-leads",
    keywords: ["callback", "sla", "cc"],
    labels: ["recently-added"],
    panel: {
      kind: "rowLog",
      storageKey: "ss_d2d_callback_tests",
      columns: [
        { id: "lead", label: "Lead / case" },
        { id: "promised", label: "Promised at" },
        { id: "actual", label: "Actual call" },
        { id: "delta", label: "Delta (min)" },
      ],
    },
  },
  {
    id: "missed-call-checker-notes",
    title: "Missed call checker",
    description: "Voicemail + CRM sync verification notes.",
    categoryId: "phone-leads",
    keywords: ["missed call", "voicemail", "crm"],
    labels: ["recently-added"],
    panel: { kind: "notes", storageKey: "ss_d2d_missed_calls", placeholder: "## Queue\n## VM transcription quality\n## CRM logging gaps\n" },
  },
  {
    id: "call-queue-test-checklist",
    title: "Call queue test checklist",
    description: "Music, overflow, and reporting checks.",
    categoryId: "phone-leads",
    keywords: ["queue", "acd", "teams voice"],
    labels: ["recently-added"],
    panel: {
      kind: "staticChecklist",
      items: [
        "Music on hold + comfort message legal review",
        "Overflow / timeout targets configured",
        "Agent presence states tested",
        "Emergency / after-hours path validated",
        "Callback offer behaves as designed",
        "Reporting interval matches ops cadence",
        "Failover trunk tested with provider",
      ],
    },
  },
  {
    id: "live-chat-response-tracker",
    title: "Live chat response tracker",
    description: "First response times by queue.",
    categoryId: "phone-leads",
    keywords: ["chat", "sla", "cx"],
    labels: ["recently-added"],
    panel: {
      kind: "rowLog",
      storageKey: "ss_d2d_chat_response",
      columns: [
        { id: "queue", label: "Queue" },
        { id: "first", label: "First response (s)" },
        { id: "agent", label: "Agent" },
        { id: "notes", label: "Notes" },
      ],
    },
  },
  {
    id: "lead-response-time-calculator",
    title: "Lead response time calculator",
    description: "Minutes between lead created and first touch — client-side math only.",
    categoryId: "phone-leads",
    keywords: ["sla", "speed to lead", "minutes"],
    labels: ["recently-added"],
    panel: { kind: "leadResponseCalculator" },
  },
  {
    id: "lead-escalation-notes",
    title: "Lead escalation notes",
    description: "Routing misses and handoff gaps.",
    categoryId: "phone-leads",
    keywords: ["escalation", "routing", "bdr"],
    labels: ["recently-added"],
    panel: { kind: "notes", storageKey: "ss_d2d_lead_escalation", placeholder: "## Lead id\n## Expected owner\n## Actual path\n## Fix\n" },
  },
  {
    id: "daily-lead-check-report-generator",
    title: "Daily lead-check report generator",
    description: "Paste counts + anomalies for leadership summary.",
    categoryId: "phone-leads",
    keywords: ["report", "leads", "daily"],
    labels: ["recently-added"],
    panel: { kind: "generator", templateId: "daily-lead-check-report" },
  },
  {
    id: "customer-service-issue-tracker",
    title: "Customer service issue tracker",
    description: "Themes, volumes, and owners.",
    categoryId: "phone-leads",
    keywords: ["cx", "themes", "support"],
    labels: ["recently-added"],
    panel: {
      kind: "rowLog",
      storageKey: "ss_d2d_cs_issues",
      columns: [
        { id: "theme", label: "Theme" },
        { id: "volume", label: "Volume" },
        { id: "owner", label: "Owner" },
        { id: "status", label: "Status" },
      ],
    },
  },
  {
    id: "call-script-notes",
    title: "Call script notes",
    description: "Iterate talk tracks with versioning in export.",
    categoryId: "phone-leads",
    keywords: ["script", "sales", "qualification"],
    labels: ["recently-added"],
    panel: { kind: "notes", storageKey: "ss_d2d_call_scripts", placeholder: "## Version\n## Opening\n## Discovery\n## Objections\n## CTA\n" },
  },
  {
    id: "twilio-integration-placeholder",
    title: "Twilio integration (placeholder)",
    description: "Backend-ready pattern for programmable voice/SMS tests.",
    categoryId: "phone-leads",
    keywords: ["twilio", "api", "pstn"],
    labels: ["recently-added", "automation-ready"],
    panel: { kind: "richPlaceholder", placeholderId: "twilio" },
  },
  {
    id: "phone-test-csv-export",
    title: "Phone test CSV export",
    description: "Dedicated log tuned for CSV hand-off to BI.",
    categoryId: "phone-leads",
    keywords: ["csv", "export", "dialer"],
    labels: ["recently-added"],
    panel: {
      kind: "rowLog",
      storageKey: "ss_d2d_phone_csv_export",
      columns: [
        { id: "ts", label: "Timestamp" },
        { id: "direction", label: "Direction" },
        { id: "from", label: "From" },
        { id: "to", label: "To" },
        { id: "result", label: "Result code" },
      ],
    },
  },
  // Finance & Life Admin Toolkit
  {
    id: "monthly-budget-planner",
    title: "Monthly budget planner",
    description: "Category rows with planned vs actual.",
    categoryId: "finance-life",
    keywords: ["budget", "categories", "monthly"],
    labels: ["recently-added"],
    panel: {
      kind: "rowLog",
      storageKey: "ss_d2d_monthly_budget",
      columns: [
        { id: "category", label: "Category" },
        { id: "planned", label: "Planned (£)" },
        { id: "actual", label: "Actual (£)" },
        { id: "notes", label: "Notes" },
      ],
    },
  },
  {
    id: "savings-pot-tracker",
    title: "Savings pot tracker",
    description: "Named pots with targets.",
    categoryId: "finance-life",
    keywords: ["savings", "pots", "goals"],
    labels: ["recently-added"],
    panel: {
      kind: "rowLog",
      storageKey: "ss_d2d_savings_pots",
      columns: [
        { id: "pot", label: "Pot" },
        { id: "target", label: "Target (£)" },
        { id: "balance", label: "Balance (£)" },
        { id: "notes", label: "Notes" },
      ],
    },
  },
  {
    id: "emergency-fund-tracker-life",
    title: "Emergency fund tracker",
    description: "Separate life-admin view from core finance hub — own storage key.",
    categoryId: "finance-life",
    keywords: ["emergency", "buffer", "runway"],
    labels: ["recently-added"],
    panel: { kind: "emergencyFund", storageKey: "ss_d2d_emergency_life" },
  },
  {
    id: "subscription-cancellation-tracker",
    title: "Subscription cancellation tracker",
    description: "Services you are exiting with confirmation refs.",
    categoryId: "finance-life",
    keywords: ["cancel", "subscription", "renewal"],
    labels: ["recently-added"],
    panel: {
      kind: "rowLog",
      storageKey: "ss_d2d_sub_cancellations",
      columns: [
        { id: "service", label: "Service" },
        { id: "requested", label: "Cancel requested" },
        { id: "confirmed", label: "Confirmed on" },
        { id: "ref", label: "Reference / ticket" },
      ],
    },
  },
  {
    id: "debt-payoff-tracker-life",
    title: "Debt payoff tracker",
    description: "Same planner as core finance tool with isolated storage for household separation.",
    categoryId: "finance-life",
    keywords: ["debt", "avalanche", "snowball"],
    labels: ["recently-added"],
    panel: { kind: "debtPlanner", storageKey: "ss_d2d_debt_life" },
  },
  {
    id: "pay-rise-calculator-life",
    title: "Pay rise calculator",
    description: "Annual delta with monthly illustration.",
    categoryId: "finance-life",
    keywords: ["salary", "raise", "tax"],
    labels: ["recently-added"],
    panel: { kind: "payRise" },
  },
  {
    id: "pension-contribution-notes",
    title: "Pension contribution notes",
    description: "Non-advice scratchpad for employer schemes.",
    categoryId: "finance-life",
    keywords: ["pension", "salary sacrifice", "avc"],
    labels: ["recently-added"],
    panel: { kind: "notes", storageKey: "ss_d2d_pension_notes", placeholder: "## Scheme\n## Employer %\n## Employee %\n## AVC ideas (non-advice)\n" },
  },
  {
    id: "investment-notes-tracker-life",
    title: "Investment notes tracker",
    description: "Isolated investment journal from core finance entry.",
    categoryId: "finance-life",
    keywords: ["invest", "portfolio", "thesis"],
    labels: ["recently-added"],
    panel: { kind: "notes", storageKey: "ss_d2d_invest_life", placeholder: "## Holdings\n## Thesis\n## Risk flags\n" },
  },
  {
    id: "weekly-savings-challenge-tracker-life",
    title: "Weekly savings challenge tracker",
    description: "Seven-day micro-goals with separate persistence.",
    categoryId: "finance-life",
    keywords: ["challenge", "habit", "weekly"],
    labels: ["recently-added"],
    panel: {
      kind: "checklist",
      storageKey: "ss_d2d_weekly_save_life",
      seedItems: ["Mon — skip impulse buy", "Tue — pack lunch", "Wed — audit one subscription", "Thu — sell / donate item", "Fri — free social plan", "Sat — meal prep", "Sun — review spending"],
    },
  },
  {
    id: "car-fund-tracker",
    title: "Car fund tracker",
    description: "Simple progress toward a vehicle goal.",
    categoryId: "finance-life",
    keywords: ["car", "fund", "savings"],
    labels: ["recently-added"],
    panel: { kind: "amountTracker", storageKey: "ss_d2d_car_fund", headline: "Car fund" },
  },
  {
    id: "holiday-fund-tracker",
    title: "Holiday fund tracker",
    description: "Track getaway savings progress.",
    categoryId: "finance-life",
    keywords: ["holiday", "vacation", "travel"],
    labels: ["recently-added"],
    panel: { kind: "amountTracker", storageKey: "ss_d2d_holiday_fund", headline: "Holiday fund" },
  },
  {
    id: "bills-checklist-life",
    title: "Bills checklist",
    description: "Monthly domestic bills sweep.",
    categoryId: "finance-life",
    keywords: ["bills", "utilities", "direct debit"],
    labels: ["recently-added"],
    panel: {
      kind: "checklist",
      storageKey: "ss_d2d_bills_life",
      seedItems: ["Rent / mortgage", "Council tax / property tax", "Utilities (gas / electric / water)", "Internet + mobile", "Insurance (home / car / health)", "Childcare / school fees", "Subscriptions audit"],
    },
  },
  {
    id: "direct-debit-tracker",
    title: "Direct debit tracker",
    description: "Mandates, amounts, and renewal windows.",
    categoryId: "finance-life",
    keywords: ["direct debit", "mandate", "bank"],
    labels: ["recently-added"],
    panel: {
      kind: "rowLog",
      storageKey: "ss_d2d_direct_debits",
      columns: [
        { id: "payee", label: "Payee" },
        { id: "amount", label: "Amount" },
        { id: "day", label: "Day of month" },
        { id: "account", label: "Paid from" },
      ],
    },
  },
  {
    id: "net-pay-notes",
    title: "Net pay notes",
    description: "Payslip deltas and tax code changes — not tax advice.",
    categoryId: "finance-life",
    keywords: ["payslip", "net pay", "tax code"],
    labels: ["recently-added"],
    panel: { kind: "notes", storageKey: "ss_d2d_net_pay", placeholder: "## Month\n## Gross / net\n## Deductions notes\n## Questions for payroll\n" },
  },
  {
    id: "financial-goals-dashboard",
    title: "Financial goals dashboard",
    description: "Goal rows with target dates.",
    categoryId: "finance-life",
    keywords: ["goals", "planning", "targets"],
    labels: ["recently-added"],
    panel: {
      kind: "rowLog",
      storageKey: "ss_d2d_fin_goals",
      columns: [
        { id: "goal", label: "Goal" },
        { id: "target", label: "Target amount" },
        { id: "by", label: "Target date" },
        { id: "status", label: "Status" },
      ],
    },
  },
  // Developer Utilities
  {
    id: "dev-json-formatter",
    title: "JSON formatter",
    description: "Developer hub entry — same behaviour as core JSON tool.",
    categoryId: "developer",
    keywords: ["json", "format", "api"],
    labels: ["most-used", "recently-added"],
    panel: { kind: "jsonTool" },
  },
  {
    id: "dev-csv-cleaner",
    title: "CSV cleaner",
    description: "Trim rows, drop empties, normalise line endings — all local.",
    categoryId: "developer",
    keywords: ["csv", "clean", "etl"],
    labels: ["recently-added"],
    panel: { kind: "csvCleaner" },
  },
  {
    id: "dev-markdown-previewer",
    title: "Markdown previewer",
    description: "Lightweight MD preview for README drafts.",
    categoryId: "developer",
    keywords: ["markdown", "readme", "docs"],
    labels: ["recently-added"],
    panel: { kind: "markdownPreview" },
  },
  {
    id: "dev-html-previewer",
    title: "HTML previewer",
    description: "Sandboxed snippet preview.",
    categoryId: "developer",
    keywords: ["html", "iframe", "email"],
    labels: ["recently-added"],
    panel: { kind: "htmlPreview" },
  },
  {
    id: "dev-css-shadow-generator",
    title: "CSS shadow generator",
    description: "Compose box-shadow values with live preview.",
    categoryId: "developer",
    keywords: ["css", "shadow", "ui"],
    labels: ["recently-added"],
    panel: { kind: "cssShadow" },
  },
  {
    id: "dev-gradient-generator",
    title: "CSS gradient generator",
    description: "Linear-gradient helper with copyable CSS.",
    categoryId: "developer",
    keywords: ["gradient", "css", "background"],
    labels: ["recently-added"],
    panel: { kind: "cssGradient" },
  },
  {
    id: "dev-regex-tester-placeholder",
    title: "Regex tester (placeholder)",
    description: "Use server-side bounded matcher — client-only placeholder.",
    categoryId: "developer",
    keywords: ["regex", "redos", "pattern"],
    labels: ["recently-added", "automation-ready"],
    panel: { kind: "apiPlaceholder", scenario: "regex-safe" },
  },
  {
    id: "dev-url-parser",
    title: "URL parser",
    description: "Splits protocol, host, path, and query keys using the URL API.",
    categoryId: "developer",
    keywords: ["url", "parse", "querystring"],
    labels: ["recently-added"],
    panel: { kind: "urlParser" },
  },
  {
    id: "dev-query-string-builder",
    title: "Query string builder",
    description: "Add key/value rows and encode safely.",
    categoryId: "developer",
    keywords: ["querystring", "search params", "encode"],
    labels: ["recently-added"],
    panel: { kind: "queryStringBuilder" },
  },
  {
    id: "dev-slug-generator",
    title: "Slug generator",
    description: "Web-safe slug from arbitrary text.",
    categoryId: "developer",
    keywords: ["slug", "seo", "routing"],
    labels: ["recently-added"],
    panel: { kind: "slugTool" },
  },
  {
    id: "dev-text-diff-checker",
    title: "Text diff checker",
    description: "Simple line-based diff in the browser.",
    categoryId: "developer",
    keywords: ["diff", "compare", "patch"],
    labels: ["recently-added"],
    panel: { kind: "textDiff" },
  },
  {
    id: "dev-word-counter",
    title: "Word counter",
    description: "Counts words and characters for drafts.",
    categoryId: "developer",
    keywords: ["word count", "characters", "copy"],
    labels: ["recently-added"],
    panel: { kind: "countTool" },
  },
  {
    id: "dev-code-snippet-library",
    title: "Code snippet library",
    description: "Label + body snippets with copy — separate from productivity library.",
    categoryId: "developer",
    keywords: ["snippets", "code", "templates"],
    labels: ["recently-added"],
    panel: { kind: "snippetLibrary", storageKey: "ss_d2d_dev_snippets" },
  },
  {
    id: "dev-api-request-notes",
    title: "API request notes",
    description: "Capture curl sketches and response notes — never store live secrets here.",
    categoryId: "developer",
    keywords: ["api", "curl", "integration"],
    labels: ["recently-added", "automation-ready"],
    panel: { kind: "notes", storageKey: "ss_d2d_api_notes", placeholder: "## Endpoint\n## Headers (no secrets)\n## Body\n## Response notes\n" },
  },
  {
    id: "dev-environment-variable-checklist",
    title: "Environment variable checklist",
    description: "Process checks before shipping integrations.",
    categoryId: "developer",
    keywords: ["env", "secrets", "ci"],
    labels: ["recently-added", "automation-ready"],
    panel: {
      kind: "staticChecklist",
      items: [
        "No secrets in NEXT_PUBLIC_* variables",
        "Preview vs production scopes separated",
        "Rotation calendar for long-lived tokens",
        "Least privilege on CI OIDC roles",
        "Audit export of who changed envs (platform log)",
        "Emergency revoke procedure rehearsed",
        "Document owner per integration",
      ],
    },
  },
  // Automation Ideas Hub
  {
    id: "auto-idea-form-automation",
    title: "Website form automation",
    description: "Headless checks for marketing forms — wire via server runner.",
    categoryId: "automation",
    keywords: ["forms", "playwright", "cron"],
    labels: ["automation-ready", "recently-added"],
    panel: { kind: "richPlaceholder", placeholderId: "form_automation" },
  },
  {
    id: "auto-idea-mxtoolbox-api",
    title: "MXToolbox API checks",
    description: "Scheduled DNS/mail diagnostics from backend jobs.",
    categoryId: "automation",
    keywords: ["dns", "mx", "api"],
    labels: ["automation-ready", "recently-added"],
    panel: { kind: "richPlaceholder", placeholderId: "mxtoolbox" },
  },
  {
    id: "auto-idea-hetrixtools",
    title: "HetrixTools blacklist monitoring",
    description: "Poll reputation lists and open incidents on listing.",
    categoryId: "automation",
    keywords: ["blacklist", "rbl", "monitoring"],
    labels: ["automation-ready", "recently-added"],
    panel: { kind: "richPlaceholder", placeholderId: "hetrixtools" },
  },
  {
    id: "auto-idea-virustotal",
    title: "VirusTotal lookup automation",
    description: "Hash and URL verdict fan-out from secure worker.",
    categoryId: "automation",
    keywords: ["virustotal", "malware", "ioc"],
    labels: ["automation-ready", "recently-added"],
    panel: { kind: "richPlaceholder", placeholderId: "virustotal" },
  },
  {
    id: "auto-idea-abuseipdb",
    title: "AbuseIPDB lookup automation",
    description: "Score inbound IPs touching public forms.",
    categoryId: "automation",
    keywords: ["abuseipdb", "reputation", "ip"],
    labels: ["automation-ready", "recently-added"],
    panel: { kind: "richPlaceholder", placeholderId: "abuseipdb" },
  },
  {
    id: "auto-idea-twilio-tests",
    title: "Twilio phone testing",
    description: "Synthetic call/SMS probes with audit logs.",
    categoryId: "automation",
    keywords: ["twilio", "pstn", "ivr"],
    labels: ["automation-ready", "recently-added"],
    panel: { kind: "richPlaceholder", placeholderId: "twilio" },
  },
  {
    id: "auto-idea-msgraph",
    title: "Microsoft Graph checks",
    description: "Delegated reads for risky sign-ins and licence deltas.",
    categoryId: "automation",
    keywords: ["graph", "entra", "sign-in"],
    labels: ["automation-ready", "recently-added"],
    panel: { kind: "richPlaceholder", placeholderId: "msgraph" },
  },
  {
    id: "auto-idea-github-actions",
    title: "GitHub Actions scheduled tests",
    description: "Nightly smoke against preview + production canaries.",
    categoryId: "automation",
    keywords: ["github actions", "ci", "schedule"],
    labels: ["automation-ready", "recently-added"],
    panel: { kind: "richPlaceholder", placeholderId: "github_actions" },
  },
  {
    id: "auto-idea-playwright",
    title: "Playwright browser tests",
    description: "Cross-browser suites with trace artifacts stored privately.",
    categoryId: "automation",
    keywords: ["playwright", "e2e", "traces"],
    labels: ["automation-ready", "recently-added"],
    panel: { kind: "richPlaceholder", placeholderId: "playwright_remote" },
  },
  {
    id: "auto-idea-csv-email-reports",
    title: "CSV email reports",
    description: "Scheduled digest of monitoring tables to secure inboxes.",
    categoryId: "automation",
    keywords: ["csv", "email", "reports"],
    labels: ["automation-ready", "recently-added"],
    panel: { kind: "richPlaceholder", placeholderId: "csv_email_reports" },
  },
  {
    id: "auto-idea-dashboard-alerts",
    title: "Dashboard alert notifications",
    description: "Webhook fan-out when checks fail.",
    categoryId: "automation",
    keywords: ["alerts", "slack", "pager"],
    labels: ["automation-ready", "recently-added"],
    panel: { kind: "richPlaceholder", placeholderId: "dashboard_alerts" },
  },
  {
    id: "auto-idea-secure-proxy",
    title: "Secure backend API proxy",
    description: "BFF that holds third-party credentials and applies authZ.",
    categoryId: "automation",
    keywords: ["proxy", "bff", "secrets"],
    labels: ["automation-ready", "recently-added"],
    panel: { kind: "richPlaceholder", placeholderId: "secure_api_proxy" },
  },
  {
    id: "auto-idea-vercel-fn",
    title: "Vercel serverless function notes",
    description: "Short-lived integration endpoints with cron protection.",
    categoryId: "automation",
    keywords: ["vercel", "serverless", "cron"],
    labels: ["automation-ready", "recently-added"],
    panel: { kind: "richPlaceholder", placeholderId: "vercel_serverless" },
  },
  {
    id: "auto-idea-netlify-fn",
    title: "Netlify function notes",
    description: "Scheduled Netlify functions hitting internal APIs.",
    categoryId: "automation",
    keywords: ["netlify", "functions", "schedule"],
    labels: ["automation-ready", "recently-added"],
    panel: { kind: "richPlaceholder", placeholderId: "netlify_functions" },
  },
  {
    id: "auto-idea-api-key-security",
    title: "API key security checklist",
    description: "Automation-facing secrets hygiene checklist.",
    categoryId: "automation",
    keywords: ["api keys", "rotation", "ci"],
    labels: ["automation-ready", "recently-added"],
    panel: { kind: "richPlaceholder", placeholderId: "api_key_hygiene" },
  },
];
