// =============================================================================
// Day-to-Day Tools — central catalog (categories + tools).
// To add a tool: append to DAY_TO_DAY_TOOLS, pick a unique `id`, assign `panel`,
// then handle any new `panel.kind` inside PanelRouter if you introduced one.
// =============================================================================

import type { DayToDayCategory, DayToDayToolDefinition } from "./types";

export const DAY_TO_DAY_CATEGORIES: DayToDayCategory[] = [
  {
    id: "productivity",
    label: "Productivity Tools",
    description: "Plan, focus, capture notes, and keep lightweight logs.",
  },
  {
    id: "work",
    label: "Work / Office Tools",
    description: "Email helpers, agendas, logs, and office templates.",
  },
  {
    id: "it-admin",
    label: "IT Admin Tools",
    description: "Checklists, trackers, and placeholders for infra lookups.",
  },
  {
    id: "marketing",
    label: "Marketing Tools",
    description: "Campaign scaffolding, captions, UTMs, and QA lists.",
  },
  {
    id: "finance",
    label: "Finance / Personal Tools",
    description: "Calculators and simple trackers for personal finance.",
  },
  {
    id: "web",
    label: "Web / Developer Tools",
    description: "Encoders, formatters, previews, and quick utilities.",
  },
];

const MFA_ITEMS = [
  "Inventory apps requiring MFA",
  "Pilot group identified and communicated",
  "Conditional Access / IdP policy drafted",
  "Break-glass accounts documented and secured",
  "Helpdesk macros and escalation path ready",
  "Reporting for registration / sign-in health",
  "Rollback plan and comms templates approved",
];

const STARTER_ITEMS = [
  "Account created in IdP / HRIS",
  "Hardware ordered or assigned",
  "Mailbox and groups membership",
  "Teams / Slack / comms access",
  "VPN / Zero Trust posture verified",
  "Security awareness assigned",
  "Manager check-in scheduled (day 3)",
];

const LEAVER_ITEMS = [
  "Termination date confirmed with HR",
  "Mailbox delegated or auto-reply configured",
  "Licences reclaimed (M365, SaaS)",
  "Device wipe / return ticket",
  "Shared mailbox / DL ownership transferred",
  "Data export policy checked (legal hold)",
  "Access reviews updated",
];

const DEVICE_ITEMS = [
  "Asset tag recorded",
  "Autopilot / MDM enrolment verified",
  "Disk encryption on and recovery escrowed",
  "Baseline apps installed",
  "Wi-Fi / certificates deployed",
  "User acceptance sign-off",
];

const BITLOCKER_ITEMS = [
  "Encryption enabled on OS volume",
  "Recovery key escrowed to tenant",
  "TPM / PIN policy matches standard",
  "Suspend / resume tested post-BIOS update",
  "Escalation path for recovery failures",
];

const LANDING_CHECKLIST = [
  "Primary CTA above the fold",
  "Hero message matches ad source",
  "Social proof (logos / quotes)",
  "Form fields minimised + consent copy",
  "Page speed / LCP checked on mobile",
  "404 / thank-you / double-submit handling",
  "Analytics + conversion events firing",
  "Privacy / cookie messaging reviewed",
];

const EMAIL_CAMPAIGN_CHECKLIST = [
  "Audience segment and exclusion rules",
  "Subject + preheader A/B plan",
  "Plain-text part included",
  "UTM parameters on all links",
  "Unsubscribe / preference centre tested",
  "Deliverability seed test (major ISPs)",
  "Proofread + legal / brand sign-off",
  "Rollback / pause criteria defined",
];

export const DAY_TO_DAY_TOOLS: DayToDayToolDefinition[] = [
  // —— Productivity ——
  {
    id: "daily-task-planner",
    title: "Daily task planner",
    description: "Lightweight checklist for today — autosaves in your browser.",
    categoryId: "productivity",
    keywords: ["tasks", "todo", "planner", "today"],
    panel: { kind: "checklist", storageKey: "ss_d2d_tasks", seedItems: ["Top 3 outcomes", "Inbox sweep", "Block time for deep work"] },
  },
  {
    id: "quick-notes",
    title: "Quick notes",
    description: "Scratchpad with local persistence.",
    categoryId: "productivity",
    keywords: ["notes", "scratchpad", "memo"],
    panel: { kind: "notes", storageKey: "ss_d2d_notes", placeholder: "Type freely…" },
  },
  {
    id: "priority-matrix",
    title: "Priority matrix",
    description: "Eisenhower quadrants for urgent vs important.",
    categoryId: "productivity",
    keywords: ["eisenhower", "urgent", "important", "matrix"],
    panel: { kind: "priorityMatrix", storageKey: "ss_d2d_matrix" },
  },
  {
    id: "meeting-notes-template",
    title: "Meeting notes template generator",
    description: "Structured notes you can paste into Docs or Notion.",
    categoryId: "productivity",
    keywords: ["meeting", "minutes", "template"],
    panel: { kind: "generator", templateId: "meeting-notes" },
  },
  {
    id: "checklist-builder",
    title: "Checklist builder",
    description: "Build your own reusable checklist.",
    categoryId: "productivity",
    keywords: ["checklist", "custom", "builder"],
    panel: { kind: "checklist", storageKey: "ss_d2d_custom_checklist" },
  },
  {
    id: "reminder-list",
    title: "Reminder list",
    description: "Simple reminders with optional due hints.",
    categoryId: "productivity",
    keywords: ["reminders", "due", "follow up"],
    panel: { kind: "reminders", storageKey: "ss_d2d_reminders" },
  },
  {
    id: "pomodoro-timer",
    title: "Pomodoro timer",
    description: "25 / 5 / 15 minute focus cycles.",
    categoryId: "productivity",
    keywords: ["pomodoro", "focus", "timer"],
    panel: { kind: "timer", variant: "pomodoro" },
  },
  {
    id: "focus-mode-timer",
    title: "Focus mode timer",
    description: "Longer deep-work sessions with stretch breaks.",
    categoryId: "productivity",
    keywords: ["deep work", "focus", "timer"],
    panel: { kind: "timer", variant: "focus" },
  },
  {
    id: "calendar-day-planner",
    title: "Calendar-style day planner",
    description: "Hour blocks from 08:00–18:00 for quick day shaping.",
    categoryId: "productivity",
    keywords: ["calendar", "hours", "schedule"],
    panel: { kind: "hourlyPlanner", storageKey: "ss_d2d_hourly" },
  },
  {
    id: "clipboard-snippets",
    title: "Copy-to-clipboard snippets",
    description: "Save short snippets and copy them in one tap.",
    categoryId: "productivity",
    keywords: ["snippets", "clipboard", "templates"],
    panel: { kind: "snippetLibrary", storageKey: "ss_d2d_snippets" },
  },
  // —— Work / Office ——
  {
    id: "email-subject-generator",
    title: "Email subject line generator",
    description: "Starter lines from topic and tone.",
    categoryId: "work",
    keywords: ["email", "subject", "outlook"],
    panel: { kind: "generator", templateId: "email-subject" },
  },
  {
    id: "email-reply-helper",
    title: "Professional email reply helper",
    description: "Polished reply scaffold from bullet context.",
    categoryId: "work",
    keywords: ["reply", "email", "professional"],
    panel: { kind: "generator", templateId: "email-reply" },
  },
  {
    id: "ooo-generator",
    title: "Out-of-office message generator",
    description: "Clear OOO with backup routing.",
    categoryId: "work",
    keywords: ["ooo", "autoreply", "leave"],
    panel: { kind: "generator", templateId: "ooo" },
  },
  {
    id: "meeting-agenda-generator",
    title: "Meeting agenda generator",
    description: "Table-style agenda from topics and duration.",
    categoryId: "work",
    keywords: ["agenda", "meeting", "facilitator"],
    panel: { kind: "generator", templateId: "agenda" },
  },
  {
    id: "follow-up-email-generator",
    title: "Follow-up email generator",
    description: "After a call or thread stalls.",
    categoryId: "work",
    keywords: ["follow up", "nudge", "email"],
    panel: { kind: "generator", templateId: "follow-up" },
  },
  {
    id: "call-log-template",
    title: "Call log template",
    description: "Track calls with outcome and next step.",
    categoryId: "work",
    keywords: ["call log", "crm", "sales"],
    panel: {
      kind: "rowLog",
      storageKey: "ss_d2d_call_log",
      columns: [
        { id: "when", label: "When" },
        { id: "who", label: "Contact" },
        { id: "summary", label: "Summary" },
        { id: "next", label: "Next step" },
      ],
    },
  },
  {
    id: "lead-check-log",
    title: "Lead check log",
    description: "Lightweight lead qualification notes.",
    categoryId: "work",
    keywords: ["lead", "bdr", "sdr"],
    panel: {
      kind: "rowLog",
      storageKey: "ss_d2d_lead_log",
      columns: [
        { id: "lead", label: "Lead" },
        { id: "source", label: "Source" },
        { id: "fit", label: "Fit / notes" },
        { id: "stage", label: "Stage" },
      ],
    },
  },
  {
    id: "daily-work-report",
    title: "Daily work report generator",
    description: "Summarise wins, blockers, and tomorrow’s plan.",
    categoryId: "work",
    keywords: ["report", "standup", "manager"],
    panel: { kind: "generator", templateId: "work-report" },
  },
  {
    id: "simple-time-tracker",
    title: "Simple time tracker",
    description: "Start/stop sessions stored locally.",
    categoryId: "work",
    keywords: ["time", "timer", "billable"],
    panel: { kind: "timeTracker", storageKey: "ss_d2d_time" },
  },
  {
    id: "file-naming-generator",
    title: "File naming generator",
    description: "Consistent, web-safe filenames.",
    categoryId: "work",
    keywords: ["filename", "naming", "assets"],
    panel: { kind: "generator", templateId: "file-name" },
  },
  // —— IT Admin ——
  {
    id: "password-generator",
    title: "Password generator",
    description: "Client-side random passwords — nothing leaves the browser.",
    categoryId: "it-admin",
    keywords: ["password", "entropy", "security"],
    panel: { kind: "passwordGen" },
  },
  {
    id: "mfa-rollout-checklist",
    title: "MFA rollout checklist",
    description: "High-level rollout gates.",
    categoryId: "it-admin",
    keywords: ["mfa", "2fa", "conditional access"],
    panel: { kind: "staticChecklist", items: MFA_ITEMS },
  },
  {
    id: "new-starter-checklist",
    title: "New starter checklist",
    description: "Onboarding tasks for IT + manager.",
    categoryId: "it-admin",
    keywords: ["onboarding", "starter", "hr"],
    panel: { kind: "staticChecklist", items: STARTER_ITEMS },
  },
  {
    id: "leaver-checklist",
    title: "Leaver checklist",
    description: "Offboarding hygiene for access and assets.",
    categoryId: "it-admin",
    keywords: ["offboarding", "leaver", "termination"],
    panel: { kind: "staticChecklist", items: LEAVER_ITEMS },
  },
  {
    id: "device-setup-checklist",
    title: "Device setup checklist",
    description: "Baseline validation for a new build.",
    categoryId: "it-admin",
    keywords: ["intune", "mdm", "laptop"],
    panel: { kind: "staticChecklist", items: DEVICE_ITEMS },
  },
  {
    id: "bitlocker-check-template",
    title: "BitLocker check template",
    description: "Encryption posture checklist.",
    categoryId: "it-admin",
    keywords: ["bitlocker", "encryption", "recovery"],
    panel: { kind: "staticChecklist", items: BITLOCKER_ITEMS },
  },
  {
    id: "m365-licence-tracker",
    title: "Microsoft 365 licence tracker",
    description: "Local table for SKU assignments — export anytime.",
    categoryId: "it-admin",
    keywords: ["m365", "licence", "sku"],
    panel: { kind: "licenseTable", storageKey: "ss_d2d_licences" },
  },
  {
    id: "dns-record-checker-placeholder",
    title: "DNS record checker (placeholder)",
    description: "UI shell for a future server-side DNS lookup — keys stay off the client.",
    categoryId: "it-admin",
    keywords: ["dns", "a record", "mx"],
    panel: { kind: "apiPlaceholder", scenario: "dns" },
  },
  {
    id: "ip-lookup-placeholder",
    title: "IP lookup (placeholder)",
    description: "Reserved for a future geo / ASN lookup route.",
    categoryId: "it-admin",
    keywords: ["ip", "asn", "geo"],
    panel: { kind: "apiPlaceholder", scenario: "ip" },
  },
  {
    id: "ports-reference-table",
    title: "Ports reference table",
    description: "Common TCP/UDP ports for triage.",
    categoryId: "it-admin",
    keywords: ["ports", "tcp", "firewall"],
    panel: { kind: "portsReference" },
  },
  {
    id: "incident-notes-template",
    title: "Incident notes template",
    description: "Free-form IR notes with export.",
    categoryId: "it-admin",
    keywords: ["incident", "ir", "sev"],
    panel: { kind: "notes", storageKey: "ss_d2d_incident", placeholder: "## Timeline\n- \n\n## Impact\n\n## Actions\n" },
  },
  // —— Marketing ——
  {
    id: "campaign-idea-generator",
    title: "Campaign idea generator",
    description: "Angles from product, audience, and constraints.",
    categoryId: "marketing",
    keywords: ["campaign", "ideas", "growth"],
    panel: { kind: "generator", templateId: "campaign-ideas" },
  },
  {
    id: "social-post-caption-helper",
    title: "Social post caption helper",
    description: "Hook + CTA scaffold.",
    categoryId: "marketing",
    keywords: ["social", "linkedin", "caption"],
    panel: { kind: "generator", templateId: "social-caption" },
  },
  {
    id: "blog-title-generator",
    title: "Blog title generator",
    description: "Five angles from a single topic.",
    categoryId: "marketing",
    keywords: ["blog", "seo", "headline"],
    panel: { kind: "generator", templateId: "blog-titles" },
  },
  {
    id: "meta-title-description-generator",
    title: "Meta title / description generator",
    description: "Length-aware title and meta description drafts.",
    categoryId: "marketing",
    keywords: ["meta", "description", "serp"],
    panel: { kind: "generator", templateId: "meta-seo" },
  },
  {
    id: "utm-builder",
    title: "UTM builder",
    description: "Build tagged campaign URLs locally.",
    categoryId: "marketing",
    keywords: ["utm", "ga4", "attribution"],
    panel: { kind: "utmBuilder" },
  },
  {
    id: "lead-source-tracker",
    title: "Lead source tracker",
    description: "Rows for channel, spend, and CPL notes.",
    categoryId: "marketing",
    keywords: ["lead source", "attribution", "cpl"],
    panel: {
      kind: "rowLog",
      storageKey: "ss_d2d_lead_sources",
      columns: [
        { id: "source", label: "Source" },
        { id: "spend", label: "Spend" },
        { id: "leads", label: "Leads" },
        { id: "notes", label: "Notes" },
      ],
    },
  },
  {
    id: "landing-page-checklist",
    title: "Landing page checklist",
    description: "Go-live QA for conversion pages.",
    categoryId: "marketing",
    keywords: ["landing", "cro", "qa"],
    panel: { kind: "staticChecklist", items: LANDING_CHECKLIST },
  },
  {
    id: "email-campaign-checklist",
    title: "Email campaign checklist",
    description: "Pre-send checks for broadcast and lifecycle.",
    categoryId: "marketing",
    keywords: ["email", "esp", "deliverability"],
    panel: { kind: "staticChecklist", items: EMAIL_CAMPAIGN_CHECKLIST },
  },
  {
    id: "ab-test-notes",
    title: "A/B test notes",
    description: "Hypothesis, variants, and readouts.",
    categoryId: "marketing",
    keywords: ["ab test", "experiment", "variant"],
    panel: { kind: "notes", storageKey: "ss_d2d_ab", placeholder: "## Hypothesis\n\n## Variants\n\n## Results\n" },
  },
  {
    id: "daily-marketing-checks-log",
    title: "Daily marketing checks log",
    description: "Date-stamped rows for channel health checks.",
    categoryId: "marketing",
    keywords: ["daily", "checks", "marketing ops"],
    panel: {
      kind: "rowLog",
      storageKey: "ss_d2d_mkt_daily",
      columns: [
        { id: "date", label: "Date" },
        { id: "channel", label: "Channel" },
        { id: "check", label: "Check" },
        { id: "status", label: "Status" },
      ],
    },
  },
  // —— Finance / Personal ——
  {
    id: "savings-goal-calculator",
    title: "Savings goal calculator",
    description: "Target amount, deadline, and monthly contribution estimate.",
    categoryId: "finance",
    keywords: ["savings", "goal", "monthly"],
    panel: { kind: "savingsCalculator" },
  },
  {
    id: "emergency-fund-tracker",
    title: "Emergency fund tracker",
    description: "Track balance vs target months of expenses.",
    categoryId: "finance",
    keywords: ["emergency", "buffer", "runway"],
    panel: { kind: "emergencyFund", storageKey: "ss_d2d_emergency" },
  },
  {
    id: "monthly-bill-checklist",
    title: "Monthly bill checklist",
    description: "Recurring bills with done toggles.",
    categoryId: "finance",
    keywords: ["bills", "subscriptions", "monthly"],
    panel: {
      kind: "checklist",
      storageKey: "ss_d2d_bills",
      seedItems: ["Rent / mortgage", "Utilities", "Internet", "Mobile", "Insurance", "Cloud / SaaS"],
    },
  },
  {
    id: "subscription-tracker",
    title: "Subscription tracker",
    description: "Service, cost, renewal cadence.",
    categoryId: "finance",
    keywords: ["subscriptions", "renewal", "cost"],
    panel: { kind: "subscriptionTable", storageKey: "ss_d2d_subs" },
  },
  {
    id: "debt-payoff-planner",
    title: "Debt payoff planner",
    description: "List debts with APR and minimums — see avalanche totals.",
    categoryId: "finance",
    keywords: ["debt", "snowball", "avalanche"],
    panel: { kind: "debtPlanner", storageKey: "ss_d2d_debt" },
  },
  {
    id: "weekly-savings-challenge-tracker",
    title: "Weekly savings challenge tracker",
    description: "Seven-day micro-goals checklist.",
    categoryId: "finance",
    keywords: ["challenge", "weekly", "habit"],
    panel: {
      kind: "checklist",
      storageKey: "ss_d2d_weekly_save",
      seedItems: ["Mon — skip impulse buy", "Tue — pack lunch", "Wed — audit one subscription", "Thu — sell / donate item", "Fri — free social plan", "Sat — meal prep", "Sun — review spending"],
    },
  },
  {
    id: "investment-notes-tracker",
    title: "Investment notes tracker",
    description: "Positions, thesis, and review dates.",
    categoryId: "finance",
    keywords: ["invest", "portfolio", "thesis"],
    panel: { kind: "notes", storageKey: "ss_d2d_invest", placeholder: "## Holdings\n\n## Thesis\n\n## Next review\n" },
  },
  {
    id: "pension-contribution-calculator-placeholder",
    title: "Pension contribution calculator (placeholder)",
    description: "Reserved for payroll / tax rules via a future API — no keys in the browser.",
    categoryId: "finance",
    keywords: ["pension", "401k", "salary sacrifice"],
    panel: { kind: "apiPlaceholder", scenario: "pension" },
  },
  {
    id: "budget-split-calculator",
    title: "Budget split calculator",
    description: "Income split across needs, wants, and savings buckets.",
    categoryId: "finance",
    keywords: ["503020", "budget", "split"],
    panel: { kind: "budgetSplit" },
  },
  {
    id: "pay-rise-calculator",
    title: "Pay rise calculator",
    description: "Old vs new salary — percent and monthly delta.",
    categoryId: "finance",
    keywords: ["salary", "raise", "percent"],
    panel: { kind: "payRise" },
  },
  // —— Web / Developer ——
  {
    id: "json-formatter",
    title: "JSON formatter",
    description: "Pretty-print or minify JSON with validation.",
    categoryId: "web",
    keywords: ["json", "format", "api"],
    panel: { kind: "jsonTool" },
  },
  {
    id: "base64-tool",
    title: "Base64 encode / decode",
    description: "UTF-8 safe transforms in the browser.",
    categoryId: "web",
    keywords: ["base64", "encode", "decode"],
    panel: { kind: "base64Tool" },
  },
  {
    id: "url-encoder-decoder",
    title: "URL encoder / decoder",
    description: "encodeURIComponent and reverse.",
    categoryId: "web",
    keywords: ["url", "encode", "querystring"],
    panel: { kind: "urlTool" },
  },
  {
    id: "slug-generator",
    title: "Slug generator",
    description: "Web-safe slugs from arbitrary titles.",
    categoryId: "web",
    keywords: ["slug", "seo", "url"],
    panel: { kind: "slugTool" },
  },
  {
    id: "case-converter",
    title: "Case converter",
    description: "camelCase, snake_case, Title, UPPER, lower.",
    categoryId: "web",
    keywords: ["case", "camel", "snake"],
    panel: { kind: "caseTool" },
  },
  {
    id: "word-character-counter",
    title: "Word / character counter",
    description: "Counts with and without whitespace.",
    categoryId: "web",
    keywords: ["count", "words", "characters"],
    panel: { kind: "countTool" },
  },
  {
    id: "regex-tester-placeholder",
    title: "Regex tester (placeholder)",
    description: "Reserved for a safe server-side regex engine — avoid ReDoS in-browser.",
    categoryId: "web",
    keywords: ["regex", "pattern", "test"],
    panel: { kind: "regexPlaceholder" },
  },
  {
    id: "markdown-preview",
    title: "Markdown preview",
    description: "Lightweight preview for common Markdown patterns.",
    categoryId: "web",
    keywords: ["markdown", "md", "preview"],
    panel: { kind: "markdownPreview" },
  },
  {
    id: "html-snippet-preview",
    title: "HTML snippet preview",
    description: "Sandboxed iframe preview — scripts stripped.",
    categoryId: "web",
    keywords: ["html", "iframe", "preview"],
    panel: { kind: "htmlPreview" },
  },
  {
    id: "colour-palette-generator",
    title: "Colour palette generator",
    description: "Harmonious hues from a base colour.",
    categoryId: "web",
    keywords: ["colour", "palette", "design"],
    panel: { kind: "colorPalette" },
  },
];

export function getDayToDayToolById(id: string): DayToDayToolDefinition | undefined {
  return DAY_TO_DAY_TOOLS.find((t) => t.id === id);
}

export function dayToDayToolSearchUrl(toolId: string): string {
  return `/day-to-day-tools?t=${encodeURIComponent(toolId)}`;
}
