"use client";

import GeneratorTool from "@/app/components/tools/GeneratorTool";

export default function MonthlyItSummaryPage() {
  return (
    <GeneratorTool
      title="Monthly IT Summary Generator"
      description="Turn raw numbers (tickets resolved, issues fixed, improvements) into a management-friendly monthly IT report."
      skill="Operations reporting, executive comms."
      why="Stops 'invisible IT'. Surfaces value and trends without burying leadership in detail."
      futureApi="Wire to ServiceNow / Jira reporting APIs to auto-populate ticket and SLA figures."
      outputBadge="Demo summary · review before circulating"
      inputs={[
        { id: "month", label: "Month / period", placeholder: "April 2026", required: true },
        { id: "tickets", label: "Tickets resolved", type: "number", placeholder: "120" },
        { id: "sla", label: "SLA % achieved", type: "number", placeholder: "97" },
        { id: "incidents", label: "Major incidents (P1/P2)", type: "number", placeholder: "0" },
        { id: "fixes", label: "Notable issues fixed (one per line)", type: "textarea", placeholder: "Replaced flaky firewall HA pair\nResolved Teams Phone routing for finance", span: "full" },
        { id: "improvements", label: "Improvements made (one per line)", type: "textarea", placeholder: "Rolled out passkeys to leadership\nAutomated daily SSL expiry check", span: "full" },
        { id: "next", label: "Next month's focus (one per line)", type: "textarea", placeholder: "Finish CA baseline\nLaunch security awareness campaign", span: "full" },
        { id: "author", label: "Report author", placeholder: "IT Manager" },
      ]}
      generate={(v) => {
        if (!v.month) return "";
        const list = (s: string) => (s || "").split(/\n+/).map((x) => x.trim()).filter(Boolean);
        const fixes = list(v.fixes);
        const improvements = list(v.improvements);
        const next = list(v.next);
        const lines: string[] = [];
        lines.push(`# IT Monthly Report — ${v.month}`);
        lines.push("");
        if (v.author) lines.push(`**Author:** ${v.author}`);
        lines.push("");
        lines.push("## At a glance");
        lines.push(`- **Tickets resolved:** ${v.tickets || "—"}`);
        lines.push(`- **SLA achieved:** ${v.sla ? `${v.sla}%` : "—"}`);
        lines.push(`- **Major incidents:** ${v.incidents ?? "—"}`);
        lines.push("");
        lines.push("## Notable issues fixed");
        if (fixes.length === 0) {
          lines.push("- _None recorded — add this month's wins._");
        } else {
          for (const f of fixes) lines.push(`- ${f}`);
        }
        lines.push("");
        lines.push("## Improvements delivered");
        if (improvements.length === 0) {
          lines.push("- _None recorded._");
        } else {
          for (const i of improvements) lines.push(`- ${i}`);
        }
        lines.push("");
        lines.push("## Risks & open items");
        lines.push("- _List the top 3 risks or open dependencies for the month ahead._");
        lines.push("");
        lines.push("## Next month's focus");
        if (next.length === 0) {
          lines.push("- _Set 3 concrete focus items for the coming month._");
        } else {
          for (const n of next) lines.push(`- ${n}`);
        }
        lines.push("");
        lines.push("---");
        lines.push("_Generated by SecureScope. Polish in your house style before circulating._");
        return lines.join("\n");
      }}
    />
  );
}
