"use client";

import MultiOutputTool from "@/app/components/tools/MultiOutputTool";

const INCIDENT_TYPES = [
  { value: "phishing", label: "Phishing email / credential harvest" },
  { value: "compromise", label: "Account compromise" },
  { value: "malware", label: "Endpoint malware" },
  { value: "data-leak", label: "Data exposure / sharing incident" },
  { value: "ransomware", label: "Ransomware" },
  { value: "other", label: "Other" },
];

const IMPACT = [
  { value: "low", label: "Low — single user, no data loss" },
  { value: "medium", label: "Medium — multiple users or limited data" },
  { value: "high", label: "High — sensitive data confirmed or service down" },
  { value: "critical", label: "Critical — confirmed exfiltration or extortion" },
];

export default function IncidentResponsePage() {
  return (
    <MultiOutputTool
      title="Microsoft 365 Incident Response Report"
      description="Generate a professional, regulator-ready incident response report covering type, impact, timeline, actions taken and recommendations."
      skill="Incident response, security operations."
      why="A clear, standard report is what auditors, insurers and execs all need — generate it from the same notes."
      futureApi="Optional: store completed reports as a SharePoint list item or push to ServiceNow via a serverless function."
      storageKey="ss.m365-incident"
      fields={[
        { id: "id", label: "Incident ID", placeholder: "INC-2026-014", defaultValue: "INC-2026-001" },
        { id: "type", label: "Incident type", type: "select", options: INCIDENT_TYPES, defaultValue: "phishing" },
        { id: "impact", label: "Impact", type: "select", options: IMPACT, defaultValue: "medium" },
        { id: "user", label: "User(s) affected", placeholder: "jane.smith@contoso.com" },
        { id: "detected", label: "Detected at", placeholder: "2026-04-19 09:14 UTC" },
        { id: "summary", label: "Summary", type: "textarea", rows: 3, placeholder: "What happened, in one paragraph." },
        { id: "actions", label: "Actions taken (one per line)", type: "textarea", rows: 5, defaultValue: "Disabled sign-in for affected user\nRevoked sessions in Entra ID\nReset password and re-registered MFA\nReviewed inbox rules and consent grants\nSearched and purged related messages with ContentSearch + PurgeRequest" },
        { id: "evidence", label: "Evidence collected (one per line)", type: "textarea", rows: 4, defaultValue: "Defender alert ID(s)\nSign-in log excerpts\nMessage trace results\nDevice telemetry from Defender for Endpoint" },
        { id: "recommendations", label: "Recommendations (one per line)", type: "textarea", rows: 4, defaultValue: "Enable phishing-resistant MFA for the affected role\nReview Conditional Access policy gap\nDeliver targeted awareness training" },
      ]}
      generate={(v) => {
        const list = (s: string) =>
          (s || "")
            .split("\n")
            .map((l) => l.trim())
            .filter(Boolean);

        const md = [
          `# Incident Response Report — ${v.id || "INC-XXXX"}`,
          ``,
          `**Type:** ${INCIDENT_TYPES.find((t) => t.value === v.type)?.label ?? v.type}`,
          `**Impact:** ${IMPACT.find((i) => i.value === v.impact)?.label ?? v.impact}`,
          `**Affected users:** ${v.user || "(not specified)"}`,
          `**Detected:** ${v.detected || "(not specified)"}`,
          `**Reported:** ${new Date().toISOString()}`,
          ``,
          `## Summary`,
          v.summary || "_(provide a one-paragraph summary)_",
          ``,
          `## Timeline`,
          `- ${v.detected || "(detection time)"} — Initial detection`,
          `- (containment timestamp) — Sign-in disabled, sessions revoked`,
          `- (eradication timestamp) — Persistence (rules, app consents) removed`,
          `- (recovery timestamp) — Account re-enabled with stronger controls`,
          ``,
          `## Actions taken`,
          ...list(v.actions).map((a) => `- ${a}`),
          ``,
          `## Evidence`,
          ...list(v.evidence).map((e) => `- ${e}`),
          ``,
          `## Recommendations`,
          ...list(v.recommendations).map((r) => `- ${r}`),
          ``,
          `## Next steps`,
          `- Schedule a 7-day follow-up sign-in audit for the user.`,
          `- Review related users for the same indicators of compromise.`,
          `- Update playbook if any step was missing or unclear.`,
          ``,
          `_Report generated by the SecureScope IT/Cyber Toolkit._`,
        ].join("\n");

        return [{ label: "Incident report (Markdown)", value: md, language: "markdown" }];
      }}
    />
  );
}
