import type { FormDefinition, FormId } from "@/lib/messaging/types";

const consentHint =
  "I agree to the processing of this request as described in the Privacy Policy. I understand this demo may log submissions server-side only for abuse prevention.";

export const FORMS: Record<FormId, FormDefinition> = {
  newsletter: {
    id: "newsletter",
    title: "Product updates",
    description: "Requires marketing consent (Cookiebot). No spam — you can withdraw anytime.",
    submitLabel: "Subscribe",
    requireConsent: true,
    requireMarketingConsent: true,
    fields: [
      { name: "email", label: "Email", type: "email", required: true, maxLength: 254 },
      { name: "_company_website", label: "Company website", type: "honeypot", required: false, maxLength: 200 },
    ],
  },
  contact: {
    id: "contact",
    title: "Contact request",
    description: "Sales, pilots, or general enquiries. No sensitive secrets in this form.",
    submitLabel: "Send request",
    requireConsent: true,
    fields: [
      { name: "name", label: "Name", type: "text", required: true, maxLength: 120 },
      { name: "email", label: "Work email", type: "email", required: true, maxLength: 254 },
      { name: "company", label: "Company", type: "text", required: false, maxLength: 160 },
      {
        name: "requestType",
        label: "Request type",
        type: "select",
        required: true,
        options: [
          { value: "sales", label: "Sales / pilot" },
          { value: "security", label: "Security review" },
          { value: "other", label: "Other" },
        ],
      },
      { name: "message", label: "Message", type: "textarea", required: true, maxLength: 4000 },
      {
        name: "priority",
        label: "Priority",
        type: "select",
        required: true,
        options: [
          { value: "normal", label: "Normal" },
          { value: "high", label: "High" },
        ],
      },
      { name: "_company_website", label: "Company website", type: "honeypot", required: false, maxLength: 200 },
    ],
  },
  "tool-feedback": {
    id: "tool-feedback",
    title: "Tool feedback",
    description: "Help us improve generators and checklists.",
    submitLabel: "Submit feedback",
    requireConsent: true,
    fields: [
      { name: "name", label: "Name", type: "text", required: true, maxLength: 120 },
      { name: "email", label: "Email", type: "email", required: true, maxLength: 254 },
      { name: "company", label: "Company", type: "text", required: false, maxLength: 160 },
      {
        name: "requestType",
        label: "Tool area",
        type: "select",
        required: true,
        options: [
          { value: "security", label: "Security tools" },
          { value: "marketing", label: "Marketing tools" },
          { value: "it", label: "IT / M365" },
          { value: "other", label: "Other" },
        ],
      },
      {
        name: "contextUrl",
        label: "Page URL (optional)",
        type: "url",
        required: false,
        maxLength: 2000,
        hint: "Paste the tool page you were using.",
      },
      { name: "message", label: "Feedback", type: "textarea", required: true, maxLength: 4000 },
      {
        name: "priority",
        label: "Priority",
        type: "select",
        required: true,
        options: [
          { value: "normal", label: "Normal" },
          { value: "high", label: "High" },
        ],
      },
      { name: "_company_website", label: "Company website", type: "honeypot", required: false, maxLength: 200 },
    ],
  },
  "bug-report": {
    id: "bug-report",
    title: "Bug report",
    description: "Repro steps help us triage quickly. Do not include passwords or API keys.",
    submitLabel: "Report bug",
    requireConsent: true,
    fields: [
      { name: "name", label: "Name", type: "text", required: true, maxLength: 120 },
      { name: "email", label: "Email", type: "email", required: true, maxLength: 254 },
      { name: "company", label: "Company", type: "text", required: false, maxLength: 160 },
      { name: "contextUrl", label: "URL where it happened", type: "url", required: false, maxLength: 2000 },
      { name: "message", label: "Steps to reproduce", type: "textarea", required: true, maxLength: 8000 },
      {
        name: "priority",
        label: "Severity",
        type: "select",
        required: true,
        options: [
          { value: "low", label: "Low" },
          { value: "normal", label: "Normal" },
          { value: "high", label: "High / blocking" },
        ],
      },
      { name: "_company_website", label: "Company website", type: "honeypot", required: false, maxLength: 200 },
    ],
  },
  "feature-request": {
    id: "feature-request",
    title: "Feature request",
    description: "Suggest a tool or workflow improvement.",
    submitLabel: "Send idea",
    requireConsent: true,
    fields: [
      { name: "name", label: "Name", type: "text", required: true, maxLength: 120 },
      { name: "email", label: "Email", type: "email", required: true, maxLength: 254 },
      { name: "company", label: "Company", type: "text", required: false, maxLength: 160 },
      { name: "message", label: "Idea", type: "textarea", required: true, maxLength: 4000 },
      {
        name: "priority",
        label: "Priority",
        type: "select",
        required: true,
        options: [
          { value: "normal", label: "Normal" },
          { value: "high", label: "High" },
        ],
      },
      { name: "_company_website", label: "Company website", type: "honeypot", required: false, maxLength: 200 },
    ],
  },
  "lead-check": {
    id: "lead-check",
    title: "Lead check request",
    description: "Request a structured review (no automated scraping from this form).",
    submitLabel: "Submit request",
    requireConsent: true,
    fields: [
      { name: "name", label: "Name", type: "text", required: true, maxLength: 120 },
      { name: "email", label: "Email", type: "email", required: true, maxLength: 254 },
      { name: "company", label: "Company", type: "text", required: true, maxLength: 160 },
      { name: "contextUrl", label: "Lead / campaign URL", type: "url", required: false, maxLength: 2000 },
      { name: "message", label: "What to validate", type: "textarea", required: true, maxLength: 4000 },
      {
        name: "priority",
        label: "Priority",
        type: "select",
        required: true,
        options: [
          { value: "normal", label: "Normal" },
          { value: "high", label: "High" },
        ],
      },
      { name: "_company_website", label: "Company website", type: "honeypot", required: false, maxLength: 200 },
    ],
  },
  "website-test": {
    id: "website-test",
    title: "Website test request",
    description: "Describe the site and scope for monitoring or QA passes.",
    submitLabel: "Submit request",
    requireConsent: true,
    fields: [
      { name: "name", label: "Name", type: "text", required: true, maxLength: 120 },
      { name: "email", label: "Email", type: "email", required: true, maxLength: 254 },
      { name: "company", label: "Company", type: "text", required: false, maxLength: 160 },
      { name: "contextUrl", label: "Website URL", type: "url", required: true, maxLength: 2000 },
      { name: "message", label: "Scope & goals", type: "textarea", required: true, maxLength: 4000 },
      {
        name: "priority",
        label: "Priority",
        type: "select",
        required: true,
        options: [
          { value: "normal", label: "Normal" },
          { value: "high", label: "High" },
        ],
      },
      { name: "_company_website", label: "Company website", type: "honeypot", required: false, maxLength: 200 },
    ],
  },
  "domain-test": {
    id: "domain-test",
    title: "Domain / DNS test request",
    description: "Public domains only — no internal hostnames.",
    submitLabel: "Submit request",
    requireConsent: true,
    fields: [
      { name: "name", label: "Name", type: "text", required: true, maxLength: 120 },
      { name: "email", label: "Email", type: "email", required: true, maxLength: 254 },
      { name: "company", label: "Company", type: "text", required: false, maxLength: 160 },
      {
        name: "contextUrl",
        label: "Domain or site URL",
        type: "url",
        required: false,
        maxLength: 2000,
        hint: "e.g. https://example.com",
      },
      { name: "message", label: "What to test", type: "textarea", required: true, maxLength: 4000 },
      {
        name: "priority",
        label: "Priority",
        type: "select",
        required: true,
        options: [
          { value: "normal", label: "Normal" },
          { value: "high", label: "High" },
        ],
      },
      { name: "_company_website", label: "Company website", type: "honeypot", required: false, maxLength: 200 },
    ],
  },
  "phone-test": {
    id: "phone-test",
    title: "Phone test request",
    description: "Describe the line and test window — no full card/SSN data.",
    submitLabel: "Submit request",
    requireConsent: true,
    fields: [
      { name: "name", label: "Name", type: "text", required: true, maxLength: 120 },
      { name: "email", label: "Email", type: "email", required: true, maxLength: 254 },
      { name: "company", label: "Company", type: "text", required: false, maxLength: 160 },
      {
        name: "phone",
        label: "E.164 phone (optional)",
        type: "tel",
        required: false,
        maxLength: 32,
        hint: "Example: +15551234567",
      },
      { name: "message", label: "Test details", type: "textarea", required: true, maxLength: 4000 },
      {
        name: "priority",
        label: "Priority",
        type: "select",
        required: true,
        options: [
          { value: "normal", label: "Normal" },
          { value: "high", label: "High" },
        ],
      },
      { name: "_company_website", label: "Company website", type: "honeypot", required: false, maxLength: 200 },
    ],
  },
  "security-check": {
    id: "security-check",
    title: "Security check request",
    description: "Scope a review (no credentials in this form).",
    submitLabel: "Submit request",
    requireConsent: true,
    fields: [
      { name: "name", label: "Name", type: "text", required: true, maxLength: 120 },
      { name: "email", label: "Email", type: "email", required: true, maxLength: 254 },
      { name: "company", label: "Company", type: "text", required: true, maxLength: 160 },
      { name: "contextUrl", label: "Environment URL (optional)", type: "url", required: false, maxLength: 2000 },
      { name: "message", label: "Scope", type: "textarea", required: true, maxLength: 4000 },
      {
        name: "priority",
        label: "Priority",
        type: "select",
        required: true,
        options: [
          { value: "normal", label: "Normal" },
          { value: "high", label: "High" },
        ],
      },
      { name: "_company_website", label: "Company website", type: "honeypot", required: false, maxLength: 200 },
    ],
  },
};

export const FORM_CONSENT_HINT = consentHint;
