// A curated subset of the EFF Short Wordlist for memorable passphrases
// Source: https://www.eff.org/deeplinks/2016/07/new-wordlists-random-passphrases
// Words chosen to be unambiguous and easy to type

export const WORDLIST: string[] = [
  "acid", "aged", "also", "area", "army", "away", "baby", "back", "ball", "band",
  "bank", "base", "bath", "bear", "beat", "been", "bell", "best", "bird", "bite",
  "blue", "boat", "body", "bold", "bone", "book", "born", "both", "bowl", "bulk",
  "burn", "busy", "cafe", "cage", "cake", "calm", "came", "camp", "card", "care",
  "cart", "cash", "cast", "cave", "chef", "chip", "cite", "city", "clam", "clap",
  "clay", "clip", "club", "coat", "code", "coil", "coin", "cold", "come", "cook",
  "cool", "core", "cork", "corn", "cost", "crab", "crew", "crop", "crow", "cube",
  "curb", "cure", "curl", "cute", "dare", "dark", "data", "date", "dawn", "days",
  "dead", "deal", "dear", "debt", "deck", "deed", "deer", "deft", "deny", "desk",
  "dial", "dice", "diet", "dirt", "disk", "dock", "does", "dome", "door", "dose",
  "dove", "down", "draw", "drew", "drip", "drop", "drum", "duck", "dusk", "dust",
  "duty", "each", "earn", "ease", "east", "edge", "else", "emit", "epic", "even",
  "ever", "exam", "exit", "eyes", "face", "fact", "fail", "fair", "fall", "fame",
  "farm", "fast", "fate", "felt", "file", "fill", "film", "find", "fine", "fire",
  "firm", "fish", "fist", "flag", "flat", "flew", "flip", "flow", "foam", "fold",
  "folk", "fond", "font", "food", "foot", "fork", "form", "fort", "foul", "four",
  "free", "from", "fuel", "full", "fund", "fuse", "gain", "game", "gang", "gear",
  "gift", "give", "glad", "glow", "glue", "gold", "golf", "gone", "good", "grab",
  "gray", "grew", "grid", "grip", "grit", "grow", "gulf", "guru", "gust", "hack",
  "hail", "half", "hall", "halt", "hand", "hang", "hard", "harm", "hash", "haze",
  "head", "heap", "heat", "heel", "help", "herb", "hero", "high", "hike", "hill",
  "hint", "hire", "hold", "hole", "home", "hook", "hope", "horn", "host", "hour",
  "huge", "hull", "hunt", "hype", "icon", "idea", "idle", "inch", "into", "iris",
  "iron", "isle", "item", "jade", "jazz", "join", "jump", "just", "keen", "keep",
  "kind", "king", "knot", "lace", "lake", "lamp", "land", "lane", "last", "lava",
  "lawn", "leaf", "lean", "leap", "left", "lend", "less", "life", "lift", "like",
  "lime", "line", "link", "lion", "list", "live", "load", "loan", "lock", "loft",
  "logo", "long", "look", "loom", "loop", "lore", "loss", "loud", "love", "luck",
  "lush", "made", "mail", "main", "make", "malt", "many", "mark", "mars", "mask",
  "mast", "math", "maze", "meal", "mean", "meet", "menu", "mesh", "mild", "mile",
  "milk", "mind", "mine", "mint", "mist", "mode", "moon", "more", "most", "move",
  "much", "mule", "must", "nail", "name", "navy", "need", "nest", "news", "next",
  "nice", "nine", "node", "none", "noon", "norm", "nose", "note", "nova", "null",
  "oath", "only", "open", "oval", "oven", "over", "page", "paid", "pain", "pair",
  "palm", "park", "part", "pass", "past", "path", "peak", "pear", "peel", "pick",
  "pier", "pine", "ping", "pink", "pipe", "plan", "play", "plot", "plow", "plum",
  "plus", "pod", "poet", "pole", "poll", "pond", "pool", "port", "post", "pour",
  "prey", "prop", "pull", "pump", "pure", "push", "quad", "race", "rack", "rain",
  "ramp", "rang", "rank", "rare", "rate", "read", "real", "reef", "rely", "rent",
  "rest", "rich", "ride", "ring", "rise", "risk", "road", "roam", "roar", "robe",
  "rock", "role", "roll", "roof", "root", "rope", "rose", "rows", "ruby", "ruin",
  "rule", "rush", "rust", "safe", "sage", "sail", "sake", "sale", "salt", "same",
  "sand", "sang", "save", "scan", "seal", "seam", "seed", "seek", "seem", "self",
  "sell", "send", "sent", "shed", "ship", "shop", "shot", "show", "shut", "sick",
  "side", "sift", "sign", "silk", "silo", "sing", "sink", "site", "size", "skin",
  "skip", "slab", "slam", "slap", "slim", "slip", "slow", "snap", "snow", "soap",
  "sock", "soft", "soil", "sold", "sole", "some", "song", "sort", "soup", "sour",
  "span", "spec", "spin", "spit", "spot", "spur", "star", "stay", "stem", "step",
  "stew", "stop", "stub", "such", "suit", "sung", "sunk", "swap", "swim", "sync",
  "tail", "take", "tale", "tall", "tank", "tarp", "task", "team", "tear", "tell",
  "tend", "tent", "term", "test", "than", "that", "them", "then", "they", "thin",
  "this", "tick", "tide", "tile", "till", "time", "tiny", "tire", "toad", "told",
  "toll", "tomb", "tone", "took", "tool", "tour", "town", "trap", "trek", "trim",
  "trio", "trip", "true", "tuck", "tuft", "tuna", "tune", "turf", "turn", "tusk",
  "twin", "type", "ugly", "undo", "unit", "upon", "user", "vain", "vale", "vary",
  "vast", "verb", "very", "vest", "view", "vine", "void", "vote", "wade", "wage",
  "wait", "wake", "walk", "wall", "wand", "warm", "warn", "warp", "wart", "wave",
  "weak", "weld", "well", "went", "were", "west", "what", "when", "whom", "wide",
  "wild", "will", "wind", "wine", "wing", "wish", "with", "wolf", "wood", "word",
  "work", "worn", "wrap", "wren", "yard", "year", "your", "zero", "zest", "zinc",
  "zone", "zoom",
];

export function randomWord(): string {
  const arr = new Uint32Array(1);
  crypto.getRandomValues(arr);
  return WORDLIST[arr[0] % WORDLIST.length];
}
