"use client";

import GeneratorTool from "@/app/components/tools/GeneratorTool";

export default function SecurityIncidentReportPage() {
  return (
    <GeneratorTool
      title="Security Incident Report Generator"
      description="Create a polished, regulator-ready security incident report covering summary, timeline, affected systems, impact, actions, recommendations and next steps."
      skill="Incident management, communications."
      why="The same incident report works for execs, auditors and insurers — generate it once."
      storageKey="ss.security-incident-report"
      fields={[
        { id: "title", label: "Incident title", placeholder: "Customer database read-only exposure", defaultValue: "Phishing-driven account compromise" },
        { id: "ref", label: "Reference / ticket #", placeholder: "SEC-2026-014" },
        { id: "severity", label: "Severity", type: "select", options: [
          { value: "SEV1", label: "SEV1 — major outage / data loss" },
          { value: "SEV2", label: "SEV2 — significant impact" },
          { value: "SEV3", label: "SEV3 — minor impact" },
          { value: "SEV4", label: "SEV4 — informational" },
        ], defaultValue: "SEV2" },
        { id: "owner", label: "Incident commander", placeholder: "@you" },
        { id: "summary", label: "Summary", type: "textarea", rows: 4, placeholder: "What happened, when, who was affected." },
        { id: "systems", label: "Affected systems / data (one per line)", type: "textarea", rows: 3 },
        { id: "impact", label: "Impact (one per line)", type: "textarea", rows: 3 },
        { id: "timeline", label: "Timeline (one event per line: 'YYYY-MM-DD HH:MM UTC — event')", type: "textarea", rows: 6, defaultValue: "2026-04-19 09:14 UTC — Defender alert raised\n2026-04-19 09:22 UTC — Account disabled, sessions revoked\n2026-04-19 10:00 UTC — Inbox rules and OAuth consents reviewed\n2026-04-19 11:30 UTC — Account re-enabled with stronger CA policy" },
        { id: "actions", label: "Actions taken (one per line)", type: "textarea", rows: 4 },
        { id: "recommendations", label: "Recommendations (one per line)", type: "textarea", rows: 4 },
        { id: "owners", label: "Recommendation owners (one per line)", type: "textarea", rows: 3 },
      ]}
      generate={(v) => {
        const list = (s: string) =>
          (s || "")
            .split("\n")
            .map((l) => l.trim())
            .filter(Boolean);

        const md = [
          `# Security Incident Report — ${v.title || "(untitled)"}`,
          ``,
          `**Reference:** ${v.ref || "(not assigned)"}`,
          `**Severity:** ${v.severity || "SEV3"}`,
          `**Incident Commander:** ${v.owner || "(not assigned)"}`,
          `**Reported:** ${new Date().toISOString()}`,
          ``,
          `## 1. Summary`,
          v.summary || "_(provide a clear, one-paragraph summary)_",
          ``,
          `## 2. Affected systems / data`,
          ...(list(v.systems).length ? list(v.systems).map((s) => `- ${s}`) : ["- (none specified)"]),
          ``,
          `## 3. Impact`,
          ...(list(v.impact).length ? list(v.impact).map((s) => `- ${s}`) : ["- (none specified)"]),
          ``,
          `## 4. Timeline`,
          ...(list(v.timeline).length ? list(v.timeline).map((s) => `- ${s}`) : ["- (no timeline provided)"]),
          ``,
          `## 5. Actions taken`,
          ...(list(v.actions).length ? list(v.actions).map((s) => `- ${s}`) : ["- (no actions documented)"]),
          ``,
          `## 6. Recommendations`,
          ...(list(v.recommendations).length
            ? list(v.recommendations).map((r, i) => `- **R${i + 1}.** ${r}${list(v.owners)[i] ? ` (owner: ${list(v.owners)[i]})` : ""}`)
            : ["- (none yet)"]),
          ``,
          `## 7. Next steps`,
          `- Schedule a 7-day post-incident review.`,
          `- Verify recommendations are tracked in the risk register / backlog.`,
          `- Communicate closure summary to stakeholders.`,
          ``,
          `_Generated by the SecureScope IT/Cyber Toolkit._`,
        ].join("\n");

        return [{ label: "Incident report (Markdown)", value: md, language: "markdown" }];
      }}
    />
  );
}
